
export let setupLinks = [
	{ label: "Setup Home", link: "/lightning/setup/SetupOneHome/home", section: "" },
	{ label: "Lightning Experience Transition Assistant", link: "/lightning/setup/EnableLightningExperience/home", section: "" },
	{ label: "Lightning Usage", link: "/lightning/setup/LightningUsageSetup/home", section: "" },
	{ label: "Permission Sets", link: "/lightning/setup/PermSets/home", section: "" },
	{ label: "Profiles", link: "/lightning/setup/Profiles/home", section: "" },
	{ label: "Public Groups", link: "/lightning/setup/PublicGroups/home", section: "" },
	{ label: "Queues", link: "/lightning/setup/Queues/home", section: "" },
	{ label: "Roles", link: "/lightning/setup/Roles/home", section: "" },
	{ label: "User Management Settings", link: "/lightning/setup/UserManagementSettings/home", section: "" },
	{ label: "Users", link: "/lightning/setup/ManageUsers/home", section: "" },
	{ label: "Big Objects", link: "/lightning/setup/BigObjects/home", section: "" },
	{ label: "Data Export", link: "/lightning/setup/DataManagementExport/home", section: "" },
	{ label: "Data Integration Metrics", link: "/lightning/setup/XCleanVitalsUi/home", section: "" },
	{ label: "Data Integration Rules", link: "/lightning/setup/CleanRules/home", section: "" },
	{ label: "Duplicate Error Logs", link: "/lightning/setup/DuplicateErrorLog/home", section: "" },
	{ label: "Duplicate Rules", link: "/lightning/setup/DuplicateRules/home", section: "" },
	{ label: "Matching Rules", link: "/lightning/setup/MatchingRules/home", section: "" },
	{ label: "Mass Delete Records", link: "/lightning/setup/DataManagementDelete/home", section: "" },
	{ label: "Mass Transfer Approval Requests", link: "/lightning/setup/DataManagementManageApprovals/home", section: "" },
	{ label: "Mass Transfer Records", link: "/lightning/setup/DataManagementTransfer/home", section: "" },
	{ label: "Mass Update Addresses", link: "/lightning/setup/DataManagementMassUpdateAddresses/home", section: "" },
	{ label: "Picklist Settings", link: "/lightning/setup/PicklistSettings/home", section: "" },
	{ label: "Schema Settings", link: "/lightning/setup/SchemaSettings/home", section: "" },
	{ label: "State and Country/Territory Picklists", link: "/lightning/setup/AddressCleanerOverview/home", section: "" },
	{ label: "Storage Usage", link: "/lightning/setup/CompanyResourceDisk/home", section: "" },
	{ label: "Apex Exception Email", link: "/lightning/setup/ApexExceptionEmail/home", section: "" },
	{ label: "Classic Email Templates", link: "/lightning/setup/CommunicationTemplatesEmail/home", section: "" },
	{ label: "Compliance BCC Email", link: "/lightning/setup/SecurityComplianceBcc/home", section: "" },
	{ label: "DKIM Keys", link: "/lightning/setup/EmailDKIMList/home", section: "" },
	{ label: "Deliverability", link: "/lightning/setup/OrgEmailSettings/home", section: "" },
	{ label: "Email Attachments", link: "/lightning/setup/EmailAttachmentSettings/home", section: "" },
	{ label: "Email Footers", link: "/lightning/setup/EmailDisclaimers/home", section: "" },
	{ label: "Email to Salesforce", link: "/lightning/setup/EmailToSalesforce/home", section: "" },
	{ label: "Enhanced Email", link: "/lightning/setup/EnhancedEmail/home", section: "" },
	{ label: "Gmail Integration and Sync", link: "/lightning/setup/LightningForGmailAndSyncSettings/home", section: "" },
	{ label: "Letterheads", link: "/lightning/setup/CommunicationTemplatesLetterheads/home", section: "" },
	{ label: "Lightning Email Templates", link: "/lightning/setup/LightningEmailTemplateSetup/home", section: "" },
	{ label: "Mail Merge Templates", link: "/lightning/setup/CommunicationTemplatesWord/home", section: "" },
	{ label: "Organization-Wide Addresses", link: "/lightning/setup/OrgWideEmailAddresses/home", section: "" },
	{ label: "Outlook Configurations", link: "/lightning/setup/EmailConfigurations/home", section: "" },
	{ label: "Outlook Integration and Sync", link: "/lightning/setup/LightningForOutlookAndSyncSettings/home", section: "" },
	{ label: "Send through External Email Services", link: "/lightning/setup/EmailTransportServiceSetupPage/home", section: "" },
	{ label: "Test Deliverability", link: "/lightning/setup/TestEmailDeliverability/home", section: "" },
	{ label: "App Manager", link: "/lightning/setup/NavigationMenus/home", section: "" },
	{ label: "AppExchange Marketplace", link: "/lightning/setup/AppExchangeMarketplace/home", section: "" },
	{ label: "Connected Apps OAuth Usage", link: "/lightning/setup/ConnectedAppsUsage/home", section: "" },
	{ label: "Manage Connected Apps", link: "/lightning/setup/ConnectedApplication/home", section: "" },
	{ label: "Installed Packages", link: "/lightning/setup/ImportedPackage/home", section: "" },
	{ label: "Flow Category", link: "/lightning/setup/FlowCategory/home", section: "Apps > Lightning Bolt" },
	{ label: "Lightning Bolt Solutions", link: "/lightning/setup/LightningBolt/home", section: "" },
	{ label: "Salesforce Branding", link: "/lightning/setup/Salesforce1Branding/home", section: "" },
	{ label: "Salesforce Mobile Quick Start", link: "/lightning/setup/Salesforce1SetupSection/home", section: "" },
	{ label: "Salesforce Navigation", link: "/lightning/setup/ProjectOneAppMenu/home", section: "" },
	{ label: "Salesforce Notifications", link: "/lightning/setup/NotificationsSettings/home", section: "" },
	{ label: "Salesforce Offline", link: "/lightning/setup/MobileOfflineStorageAdmin/home", section: "" },
	{ label: "Salesforce Settings", link: "/lightning/setup/Salesforce1Settings/home", section: "" },
	{ label: "Package Manager", link: "/lightning/setup/Package/home", section: "" },
	{ label: "Communities Settings", link: "/lightning/setup/SparkSetupPage/home", section: "" },
	{ label: "Home", link: "/lightning/setup/Home/home", section: "" },
	{ label: "Office 365", link: "/lightning/setup/NetworkSettings/home", section: "" },
	{ label: "Skype for Salesforce", link: "/lightning/setup/SkypeSetupPage/home", section: "" },
	{ label: "Quip", link: "/lightning/setup/QuipSetupAssistant/home", section: "" },
	{ label: "Asset Files", link: "/lightning/setup/ContentAssets/home", section: "" },
	{ label: "Content Deliveries and Public Links", link: "/lightning/setup/ContentDistribution/home", section: "" },
	{ label: "Files Connect", link: "/lightning/setup/ContentHub/home", section: "" },
	{ label: "General Settings", link: "/lightning/setup/FilesGeneralSettings/home", section: "" },
	{ label: "Regenerate Previews", link: "/lightning/setup/RegeneratePreviews/home", section: "" },
	{ label: "Salesforce CRM Content", link: "/lightning/setup/SalesforceCRMContent/home", section: "" },
	{ label: "Synonyms", link: "/lightning/setup/ManageSynonyms/home", section: "" },
	{ label: "Case Assignment Rules", link: "/lightning/setup/CaseRules/home", section: "" },
	{ label: "Case Auto-Response Rules", link: "/lightning/setup/CaseResponses/home", section: "" },
	{ label: "Case Comment Triggers", link: "/lightning/setup/CaseCommentTriggers/home", section: "" },
	{ label: "Case Team Roles", link: "/lightning/setup/CaseTeamRoles/home", section: "" },
	{ label: "Predefined Case Teams", link: "/lightning/setup/CaseTeamTemplates/home", section: "" },
	{ label: "Contact Roles on Cases", link: "/lightning/setup/CaseContactRoles/home", section: "" },
	{ label: "Customer Contact Requests", link: "/lightning/setup/ContactRequestFlows/home", section: "" },
	{ label: "Email-to-Case", link: "/lightning/setup/EmailToCase/home", section: "" },
	{ label: "Escalation Rules", link: "/lightning/setup/CaseEscRules/home", section: "" },
	{ label: "Feed Filters", link: "/lightning/setup/FeedFilterDefinitions/home", section: "" },
	{ label: "Field Service Settings", link: "/lightning/setup/FieldServiceSettings/home", section: "" },
	{ label: "Macro Settings", link: "/lightning/setup/MacroSettings/home", section: "" },
	{ label: "Omni-Channel Settings", link: "/lightning/setup/OmniChannelSettings/home", section: "" },
	{ label: "Snap-ins", link: "/lightning/setup/Snap-ins/home", section: "" },
	{ label: "Social Business Rules", link: "/lightning/setup/SocialCustomerServiceBusinessRules/home", section: "" },
	{ label: "Social Customer Service", link: "/lightning/setup/SocialCustomerManagementAccountSettings/home", section: "" },
	{ label: "Support Processes", link: "/lightning/setup/CaseProcess/home", section: "" },
	{ label: "Support Settings", link: "/lightning/setup/CaseSettings/home", section: "" },
	{ label: "Web-to-Case", link: "/lightning/setup/CaseWebtocase/home", section: "" },
	{ label: "Web-to-Case HTML Generator", link: "/lightning/setup/CaseWebToCaseHtmlGenerator/home", section: "" },
	{ label: "Survey Settings", link: "/lightning/setup/SurveySettings/home", section: "" },
	{ label: "Object Manager", link: "/lightning/setup/ObjectManager/home", section: "" },
	{ label: "Picklist Value Sets", link: "/lightning/setup/Picklists/home", section: "" },
	{ label: "Schema Builder", link: "/lightning/setup/SchemaBuilder/home", section: "" },

	//Process Automation
	{ label: "Approval Processes", link: "/lightning/setup/ApprovalProcesses/home", section: "Process Automation" },
	{ label: "Automation Home", link: "/lightning/setup/ProcessHome/home", section: "Process Automation" },
	{ label: "Flows", link: "/lightning/setup/Flows/home", section: "Process Automation" },
	{ label: "Migrate to Flow", link: "/lightning/setup/MigrateToFlowTool/home", section: "Process Automation" },
	{ label: "Next Best Action", link: "/lightning/setup/NextBestAction/home", section: "Process Automation" },
	{ label: "Paused And Failed Flow Interviews", link: "/lightning/setup/Pausedflows/home", section: "Process Automation" },
	{ label: "Post Templates", link: "/lightning/setup/FeedTemplates/home", section: "Process Automation" },
	{ label: "Process Automation Settings", link: "/lightning/setup/WorkflowSettings/home", section: "Process Automation" },
	{ label: "Process Builder", link: "/lightning/setup/ProcessAutomation/home", section: "Process Automation" },

	{ label: "Email Alerts", link: "/lightning/setup/WorkflowEmails/home", section: "Process Automation > Workflow Actions" },
	{ label: "Field Updates", link: "/lightning/setup/WorkflowFieldUpdates/home", section: "Process Automation > Workflow Actions" },
	{ label: "Outbound Messages", link: "/lightning/setup/WorkflowOutboundMessaging/home", section: "Process Automation > Workflow Actions" },
	{ label: "Send Actions", link: "/lightning/setup/SendAction/home", section: "Process Automation > Workflow Actions" },
	{ label: "Tasks", link: "/lightning/setup/WorkflowTasks/home", section: "Process Automation > Workflow Actions" },
	{ label: "Workflow Rules", link: "/lightning/setup/WorkflowRules/home", section: "Process Automation" },

	{ label: "Action Link Templates", link: "/lightning/setup/ActionLinkGroupTemplates/home", section: "" },
	{ label: "App Menu", link: "/lightning/setup/AppMenu/home", section: "" },
	{ label: "Custom Labels", link: "/lightning/setup/ExternalStrings/home", section: "" },
	{ label: "Density Settings", link: "/lightning/setup/DensitySetup/home", section: "" },
	{ label: "Global Actions", link: "/lightning/setup/GlobalActions/home", section: "" },
	{ label: "Publisher Layouts", link: "/lightning/setup/GlobalPublisherLayouts/home", section: "" },
	{ label: "Guided Actions", link: "/lightning/setup/GuidedActions/home", section: "" },
	{ label: "Lightning App Builder", link: "/lightning/setup/FlexiPageList/home", section: "" },
	{ label: "Path Settings", link: "/lightning/setup/PathAssistantSetupHome/home", section: "" },
	{ label: "Quick Text Settings", link: "/lightning/setup/LightningQuickTextSettings/home", section: "" },
	{ label: "Rename Tabs and Labels", link: "/lightning/setup/RenameTab/home", section: "" },
	{ label: "Custom URLs", link: "/lightning/setup/DomainSites/home", section: "" },
	{ label: "Domains", link: "/lightning/setup/DomainNames/home", section: "" },
	{ label: "Sites", link: "/lightning/setup/CustomDomain/home", section: "" },
	{ label: "Tabs", link: "/lightning/setup/CustomTabs/home", section: "" },
	{ label: "Themes and Branding", link: "/lightning/setup/ThemingAndBranding/home", section: "" },
	{ label: "Export", link: "/lightning/setup/LabelWorkbenchExport/home", section: "" },
	{ label: "Import", link: "/lightning/setup/LabelWorkbenchImport/home", section: "" },
	{ label: "Override", link: "/lightning/setup/LabelWorkbenchOverride/home", section: "" },
	{ label: "Translate", link: "/lightning/setup/LabelWorkbenchTranslate/home", section: "" },
	{ label: "Translation Settings", link: "/lightning/setup/LabelWorkbenchSetup/home", section: "" },
	{ label: "User Interface", link: "/lightning/setup/UserInterfaceUI/home", section: "" },
	{ label: "Apex Classes", link: "/lightning/setup/ApexClasses/home", section: "" },
	{ label: "Apex Hammer Test Results", link: "/lightning/setup/ApexHammerResultStatus/home", section: "" },
	{ label: "Apex Settings", link: "/lightning/setup/ApexSettings/home", section: "" },
	{ label: "Apex Test Execution", link: "/lightning/setup/ApexTestQueue/home", section: "" },
	{ label: "Apex Test History", link: "/lightning/setup/ApexTestHistory/home", section: "" },
	{ label: "Apex Triggers", link: "/lightning/setup/ApexTriggers/home", section: "" },
	{ label: "Canvas App Previewer", link: "/lightning/setup/CanvasPreviewerUi/home", section: "" },
	{ label: "Custom Metadata Types", link: "/lightning/setup/CustomMetadata/home", section: "" },
	{ label: "Custom Permissions", link: "/lightning/setup/CustomPermissions/home", section: "" },
	{ label: "Custom Settings", link: "/lightning/setup/CustomSettings/home", section: "" },
	{ label: "Email Services", link: "/lightning/setup/EmailToApexFunction/home", section: "" },
	{ label: "Debug Mode", link: "/lightning/setup/UserDebugModeSetup/home", section: "" },
	{ label: "Lightning Components", link: "/lightning/setup/LightningComponentBundles/home", section: "" },
	{ label: "Platform Cache", link: "/lightning/setup/PlatformCache/home", section: "" },
	{ label: "Remote Access", link: "/lightning/setup/RemoteAccess/home", section: "" },
	{ label: "Static Resources", link: "/lightning/setup/StaticResources/home", section: "" },
	{ label: "Tools", link: "/lightning/setup/ClientDevTools/home", section: "" },
	{ label: "Visualforce Components", link: "/lightning/setup/ApexComponents/home", section: "" },
	{ label: "Visualforce Pages", link: "/lightning/setup/ApexPages/home", section: "" },
	{ label: "Dev Hub", link: "/lightning/setup/DevHub/home", section: "" },
	{ label: "Inbound Change Sets", link: "/lightning/setup/InboundChangeSet/home", section: "" },
	{ label: "Outbound Change Sets", link: "/lightning/setup/OutboundChangeSet/home", section: "" },
	{ label: "Deployment Settings", link: "/lightning/setup/DeploymentSettings/home", section: "" },
	{ label: "Deployment Status", link: "/lightning/setup/DeployStatus/home", section: "Environments > Deploy" },
	{ label: "Apex Flex Queue", link: "/lightning/setup/ApexFlexQueue/home", section: "" },
	{ label: "Apex Jobs", link: "/lightning/setup/AsyncApexJobs/home", section: "" },
	{ label: "Background Jobs", link: "/lightning/setup/ParallelJobsStatus/home", section: "" },
	{ label: "Bulk Data Load Jobs", link: "/lightning/setup/AsyncApiJobStatus/home", section: "" },
	{ label: "Scheduled Jobs", link: "/lightning/setup/ScheduledJobs/home", section: "" },
	{ label: "Debug Logs", link: "/lightning/setup/ApexDebugLogs/home", section: "" },
	{ label: "Email Log Files", link: "/lightning/setup/EmailLogFiles/home", section: "" },
	{ label: "API Usage Notifications", link: "/lightning/setup/MonitoringRateLimitingNotification/home", section: "" },
	{ label: "Case Escalations", link: "/lightning/setup/DataManagementManageCaseEscalation/home", section: "" },
	{ label: "Email Snapshots", link: "/lightning/setup/EmailCapture/home", section: "" },
	{ label: "Outbound Messages", link: "/lightning/setup/WorkflowOmStatus/home", section: "" },
	{ label: "Time-Based Workflow", link: "/lightning/setup/DataManagementManageWorkflowQueue/home", section: "" },
	{ label: "Sandboxes", link: "/lightning/setup/DataManagementCreateTestInstance/home", section: "" },
	{ label: "System Overview", link: "/lightning/setup/SystemOverview/home", section: "" },
	{ label: "Adoption Assistance", link: "/lightning/setup/AdoptionAssistance/home", section: "" },
	{ label: "Help Menu", link: "/lightning/setup/HelpMenu/home", section: "" },
	{ label: "API", link: "/lightning/setup/WebServices/home", section: "" },
	{ label: "Change Data Capture", link: "/lightning/setup/CdcObjectEnablement/home", section: "" },
	{ label: "Data Import Wizard", link: "/lightning/setup/DataManagementDataImporter/home", section: "" },
	{ label: "Data Loader", link: "/lightning/setup/DataLoader/home", section: "" },
	{ label: "Dataloader.io", link: "/lightning/setup/DataLoaderIo/home", section: "" },
	{ label: "External Data Sources", link: "/lightning/setup/ExternalDataSource/home", section: "" },
	{ label: "External Objects", link: "/lightning/setup/ExternalObjects/home", section: "" },
	{ label: "External Services", link: "/lightning/setup/ExternalServices/home", section: "" },
	{ label: "Platform Events", link: "/lightning/setup/EventObjects/home", section: "" },
	{ label: "Business Hours", link: "/lightning/setup/BusinessHours/home", section: "" },
	{ label: "Public Calendars and Resources", link: "/lightning/setup/Calendars/home", section: "" },
	{ label: "Company Information", link: "/lightning/setup/CompanyProfileInfo/home", section: "" },
	{ label: "Critical Updates", link: "/lightning/setup/CriticalUpdates/home", section: "" },
	{ label: "Data Protection and Privacy", link: "/lightning/setup/ConsentManagement/home", section: "" },
	{ label: "Fiscal Year", link: "/lightning/setup/ForecastFiscalYear/home", section: "" },
	{ label: "Holidays", link: "/lightning/setup/Holiday/home", section: "" },
	{ label: "Language Settings", link: "/lightning/setup/LanguageSettings/home", section: "" },
	{ label: "Maps and Location Settings", link: "/lightning/setup/MapsAndLocationServicesSettings/home", section: "" },
	{ label: "My Domain", link: "/lightning/setup/OrgDomain/home", section: "" },
	{ label: "Data Classification (Beta)", link: "/lightning/setup/DataClassificationSettings/home", section: "" },
	{ label: "Data Classification Download", link: "/lightning/setup/DataClassificationDownload/home", section: "" },
	{ label: "Data Classification Upload", link: "/lightning/setup/DataClassificationUpload/home", section: "" },
	{ label: "Auth. Providers", link: "/lightning/setup/AuthProviders/home", section: "" },
	{ label: "Identity Provider", link: "/lightning/setup/IdpPage/home", section: "" },
	{ label: "Identity Provider Event Log", link: "/lightning/setup/IdpErrorLog/home", section: "" },
	{ label: "Identity Verification", link: "/lightning/setup/IdentityVerification/home", section: "" },
	{ label: "Identity Verification History", link: "/lightning/setup/VerificationHistory/home", section: "" },
	{ label: "Login Flows", link: "/lightning/setup/LoginFlow/home", section: "" },
	{ label: "Login History", link: "/lightning/setup/OrgLoginHistory/home", section: "" },
	{ label: "Single Sign-On Settings", link: "/lightning/setup/SingleSignOn/home", section: "" },
	{ label: "Activations", link: "/lightning/setup/ActivatedIpAddressAndClientBrowsersPage/home", section: "" },
	{ label: "CORS", link: "/lightning/setup/CorsWhitelistEntries/home", section: "" },
	{ label: "CSP Trusted Sites", link: "/lightning/setup/SecurityCspTrustedSite/home", section: "" },
	{ label: "Certificate and Key Management", link: "/lightning/setup/CertificatesAndKeysManagement/home", section: "" },
	{ label: "Delegated Administration", link: "/lightning/setup/DelegateGroups/home", section: "" },
	{ label: "Event Monitoring Settings", link: "/lightning/setup/EventMonitoringSetup/home", section: "" },
	{ label: "Expire All Passwords", link: "/lightning/setup/SecurityExpirePasswords/home", section: "" },
	{ label: "Field Accessibility", link: "/lightning/setup/FieldAccessibility/home", section: "" },
	{ label: "File Upload and Download Security", link: "/lightning/setup/FileTypeSetting/home", section: "" },
	{ label: "Health Check", link: "/lightning/setup/HealthCheck/home", section: "" },
	{ label: "Login Access Policies", link: "/lightning/setup/LoginAccessPolicies/home", section: "" },
	{ label: "Named Credentials", link: "/lightning/setup/NamedCredential/home", section: "" },
	{ label: "Network Access", link: "/lightning/setup/NetworkAccess/home", section: "" },
	{ label: "Password Policies", link: "/lightning/setup/SecurityPolicies/home", section: "" },
	{ label: "Remote Site Settings", link: "/lightning/setup/SecurityRemoteProxy/home", section: "" },
	{ label: "Session Management", link: "/lightning/setup/SessionManagementPage/home", section: "" },
	{ label: "Session Settings", link: "/lightning/setup/SecuritySession/home", section: "" },
	{ label: "Sharing Settings", link: "/lightning/setup/SecuritySharing/home", section: "" },
	{ label: "View Setup Audit Trail", link: "/lightning/setup/SecurityEvents/home", section: "" },
	{ label: "Optimizer", link: "/lightning/setup/SalesforceOptimizer/home", section: "" },
	{ label: "Task Fields", link: "/lightning/setup/ObjectManager/Task/FieldsAndRelationships/view", section: "" },
	{ label: "Activity Custom Fields", link: "/lightning/setup/ObjectManager/Task/FieldsAndRelationships/view", section: "" },
	{ label: "Task Page Layouts", link: "/lightning/setup/ObjectManager/Task/PageLayouts/view", section: "" },
	{ label: "Task Buttons, Links, and Actions", link: "/lightning/setup/ObjectManager/Task/ButtonsLinksActions/view", section: "" },
	{ label: "Task Compact Layouts", link: "/lightning/setup/ObjectManager/Task/CompactLayouts/view", section: "" },
	{ label: "Task Field Sets", link: "/lightning/setup/ObjectManager/Task/FieldSets/view", section: "" },
	{ label: "Task Limits", link: "/lightning/setup/ObjectManager/Task/Limits/view", section: "" },
	{ label: "Task Record Types", link: "/lightning/setup/ObjectManager/Task/RecordTypes/view", section: "" },
	{ label: "Task Related Lookup Filters", link: "/lightning/setup/ObjectManager/Task/RelatedLookupFilters/view", section: "" },
	{ label: "Task Search Layouts", link: "/lightning/setup/ObjectManager/Task/SearchLayouts/view", section: "" },
	{ label: "Task Triggers", link: "/lightning/setup/ObjectManager/Task/Triggers/view", section: "" },
	{ label: "Task Validation Rules", link: "/lightning/setup/ObjectManager/Task/ValidationRules/view", section: "" },
	{ label: "Event Fields", link: "/lightning/setup/ObjectManager/Event/FieldsAndRelationships/view", section: "" },
	{ label: "Event Page Layouts", link: "/lightning/setup/ObjectManager/Event/PageLayouts/view", section: "" },
	{ label: "Event Buttons, Links, and Actions", link: "/lightning/setup/ObjectManager/Event/ButtonsLinksActions/view", section: "" },
	{ label: "Event Compact Layouts", link: "/lightning/setup/ObjectManager/Event/CompactLayouts/view", section: "" },
	{ label: "Event Field Sets", link: "/lightning/setup/ObjectManager/Event/FieldSets/view", section: "" },
	{ label: "Event Limits", link: "/lightning/setup/ObjectManager/Event/Limits/view", section: "" },
	{ label: "Event Record Types", link: "/lightning/setup/ObjectManager/Event/RecordTypes/view", section: "" },
	{ label: "Event Related Lookup Filters", link: "/lightning/setup/ObjectManager/Event/RelatedLookupFilters/view", section: "" },
	{ label: "Event Search Layouts", link: "/lightning/setup/ObjectManager/Event/SearchLayouts/view", section: "" },
	{ label: "Event Triggers", link: "/lightning/setup/ObjectManager/Event/Triggers/view", section: "" },
	{ label: "Event Validation Rules", link: "/lightning/setup/ObjectManager/Event/ValidationRules/view", section: "" }
]