
export let setupLinks = [
  //Setup
  {label: "Setup Home", link: "/lightning/setup/SetupOneHome/home", section: "Setup", prod: false},
  {label: "Service Setup Assistant", link: "/lightning/setup/ServiceHome/home", section: "Setup", prod: false},
  {label: "Service Setup", link: "/lightning/setup/SetupOneHome/home", section: "Setup", prod: false},
  {label: "Multi-Factor Authentication Assistant", link: "/lightning/setup/MfaAssistant/home", section: "Setup", prod: false},
  {label: "Release Updates", link: "/lightning/setup/ReleaseUpdates/home", section: "Setup", prod: false},
  {label: "Salesforce Mobile App", link: "/lightning/setup/SalesforceMobileAppQuickStart/home", section: "Setup", prod: false},
  {label: "Optimizer", link: "/lightning/setup/SalesforceOptimizer/home", section: "Setup", prod: false},

  //Administration > Users
  {label: "Permission Sets Groups", link: "/lightning/setup/PermSetGroups/home", section: "Administration > Users", prod: false},
  {label: "Permission Sets", link: "/lightning/setup/PermSets/home", section: "Administration > Users", prod: false},
  {label: "Profiles", link: "/lightning/setup/Profiles/home", section: "Administration > Users", prod: false},
  {label: "Profiles (Enhanced)", link: "/lightning/setup/EnhancedProfiles/home", section: "Administration > Users", prod: false},
  {label: "Public Groups", link: "/lightning/setup/PublicGroups/home", section: "Administration > Users", prod: false},
  {label: "Queues", link: "/lightning/setup/Queues/home", section: "Administration > Users", prod: false},
  {label: "Roles", link: "/lightning/setup/Roles/home", section: "Administration > Users", prod: false},
  {label: "User Management Settings", link: "/lightning/setup/UserManagementSettings/home", section: "Administration > Users", prod: false},
  {label: "Users", link: "/lightning/setup/ManageUsers/home", section: "Administration > Users", prod: false},
  //Administration > Data
  {label: "Big Objects", link: "/lightning/setup/BigObjects/home", section: "Administration > Data", prod: false},
  {label: "Data Export", link: "/lightning/setup/DataManagementExport/home", section: "Administration > Data", prod: false},
  {label: "Data Integration Metrics", link: "/lightning/setup/XCleanVitalsUi/home", section: "Administration > Data", prod: false},
  {label: "Data Integration Rules", link: "/lightning/setup/CleanRules/home", section: "Administration > Data", prod: false},
  //Administration > Data > Duplicate Management
  {label: "Duplicate Error Logs", link: "/lightning/setup/DuplicateErrorLog/home", section: "Administration > Data > Duplicate Management", prod: false},
  {label: "Duplicate Rules", link: "/lightning/setup/DuplicateRules/home", section: "Administration > Data > Duplicate Management", prod: false},
  {label: "Matching Rules", link: "/lightning/setup/MatchingRules/home", section: "Administration > Data > Duplicate Management", prod: false},
  //Administration > Data
  {label: "Mass Delete Records", link: "/lightning/setup/DataManagementDelete/home", section: "Administration > Data", prod: false},
  {label: "Mass Transfer Approval Requests", link: "/lightning/setup/DataManagementManageApprovals/home", section: "Administration > Data", prod: false},
  {label: "Mass Transfer Records", link: "/lightning/setup/DataManagementTransfer/home", section: "Administration > Data", prod: false},
  {label: "Mass Update Addresses", link: "/lightning/setup/DataManagementMassUpdateAddresses/home", section: "Administration > Data", prod: false},
  {label: "Picklist Settings", link: "/lightning/setup/PicklistSettings/home", section: "Administration > Data", prod: false},
  {label: "Schema Settings", link: "/lightning/setup/SchemaSettings/home", section: "Administration > Data", prod: false},
  {label: "State and Country/Territory Picklists", link: "/lightning/setup/AddressCleanerOverview/home", section: "Administration > Data", prod: false},
  {label: "Storage Usage", link: "/lightning/setup/CompanyResourceDisk/home", section: "Administration > Data", prod: false},
  //Administration > Email
  {label: "Apex Exception Email", link: "/lightning/setup/ApexExceptionEmail/home", section: "Administration > Email", prod: false},
  {label: "Classic Email Templates", link: "/lightning/setup/CommunicationTemplatesEmail/home", section: "Administration > Email", prod: false},
  {label: "Compliance BCC Email", link: "/lightning/setup/SecurityComplianceBcc/home", section: "Administration > Email", prod: false},
  {label: "DKIM Keys", link: "/lightning/setup/EmailDKIMList/home", section: "Administration > Email", prod: false},
  {label: "Deliverability", link: "/lightning/setup/OrgEmailSettings/home", section: "Administration > Email", prod: false},
  {label: "Email Attachments", link: "/lightning/setup/EmailAttachmentSettings/home", section: "Administration > Email", prod: false},
  //Administration > Email > Delivery Settings
  {label: "Email Domain Filters", link: "/lightning/setup/EmailDomainFilter/home", section: "Administration > Email > Delivery Settings", prod: false},
  {label: "Email Relays", link: "/lightning/setup/EmailRelay/home", section: "Administration > Email > Delivery Settings", prod: false},
  //Administration >Email
  {label: "Email Footers", link: "/lightning/setup/EmailDisclaimers/home", section: "Administration > Email", prod: false},
  {label: "Email to Salesforce", link: "/lightning/setup/EmailToSalesforce/home", section: "Administration > Email", prod: false},
  {label: "Enhanced Email", link: "/lightning/setup/EnhancedEmail/home", section: "Administration > Email", prod: false},
  {label: "Gmail Integration and Sync", link: "/lightning/setup/LightningForGmailAndSyncSettings/home", section: "Administration > Email", prod: false},
  {label: "Letterheads", link: "/lightning/setup/CommunicationTemplatesLetterheads/home", section: "Administration > Email", prod: false},
  {label: "Lightning Email Templates", link: "/lightning/setup/LightningEmailTemplateSetup/home", section: "Administration > Email", prod: false},
  {label: "Mail Merge Templates", link: "/lightning/setup/CommunicationTemplatesWord/home", section: "Administration > Email", prod: false},
  {label: "Organization-Wide Addresses", link: "/lightning/setup/OrgWideEmailAddresses/home", section: "Administration > Email", prod: false},
  {label: "Outlook Configurations", link: "/lightning/setup/EmailConfigurations/home", section: "Administration > Email", prod: false},
  {label: "Outlook Integration and Sync", link: "/lightning/setup/LightningForOutlookAndSyncSettings/home", section: "Administration > Email", prod: false},
  {label: "Send through External Email Services", link: "/lightning/setup/EmailTransportServiceSetupPage/home", section: "Administration > Email", prod: false},
  {label: "Test Deliverability", link: "/lightning/setup/TestEmailDeliverability/home", section: "Administration > Email", prod: false},

  //Platform Tools > Apps
  {label: "App Manager", link: "/lightning/setup/NavigationMenus/home", section: "Platform Tools > Apps", prod: false},
  {label: "AppExchange Marketplace", link: "/lightning/setup/AppExchangeMarketplace/home", section: "Platform Tools > Apps", prod: false},
  //Platform Tools > Apps > Connected Apps
  {label: "Connected Apps OAuth Usage", link: "/lightning/setup/ConnectedAppsUsage/home", section: "Platform Tools > Apps > Connected Apps", prod: false},
  {label: "Manage Connected Apps", link: "/lightning/setup/ConnectedApplication/home", section: "Platform Tools > Apps > Connected Apps", prod: false},
  //Platform Tools > Apps > Lightning Bolt
  {label: "Flow Category", link: "/lightning/setup/FlowCategory/home", section: "Platform Tools > Apps > Lightning Bolt", prod: false},
  {label: "Lightning Bolt Solutions", link: "/lightning/setup/LightningBolt/home", section: "Platform Tools > Apps > Lightning Bolt", prod: false},
  //Platform Tools > Apps > Mobile Apps > Salesforce
  {label: "Salesforce Branding", link: "/lightning/setup/Salesforce1Branding/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Mobile Quick Start", link: "/lightning/setup/Salesforce1SetupSection/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Navigation", link: "/lightning/setup/ProjectOneAppMenu/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Notifications", link: "/lightning/setup/NotificationsSettings/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Offline", link: "/lightning/setup/MobileOfflineStorageAdmin/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Settings", link: "/lightning/setup/Salesforce1Settings/home", section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  //Platform Tools > Apps > Packaging
  {label: "Installed Packages", link: "/lightning/setup/ImportedPackage/home", section: "Platform Tools > Apps > Packaging", prod: false},
  {label: "Package Manager", link: "/lightning/setup/Package/home", section: "Platform Tools > Apps > Packaging", prod: false},
  {label: "Package Usage", link: "/lightning/setup/PackageUsageSummary/home", section: "Platform Tools > Apps > Packaging", prod: false},

  //Platform Tools > Feature Settings > Digital Experiences
  {label: "All Sites", link: "/lightning/setup/SetupNetworks/home", section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Pages", link: "/lightning/setup/CommunityFlexiPageList/home", section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Settings", link: "/lightning/setup/NetworkSettings/home", section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Templates", link: "/lightning/setup/CommunityTemplateDefinitionList/home", section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Themes", link: "/lightning/setup/CommunityThemeDefinitionList/home", section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},

  //Platform Tools > Feature Settings
  {label: "Field History Tracking", link: "/lightning/setup/FieldHistoryTracking/home", section: "Platform Tools > Feature Settings", prod: false},
  {label: "Functions", link: "/lightning/setup/Functions/home", section: "Platform Tools > Feature Settings", prod: false},
  {label: "Home", link: "/lightning/setup/Home/home", section: "Platform Tools > Feature Settings", prod: false},
  {label: "Quip (Salesforce Anywhere)", link: "/lightning/setup/SalesforceAnywhereSetupPage/home", section: "Platform Tools > Feature Settings", prod: false},

  //Platform Tools > Einstein > Einstein Assessors
  {label: "Einstein Bots Assessor", link: "/lightning/setup/EinsteinBotsReadinessCheck/home", section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Einstein Conversation Insights Assessor", link: "/lightning/setup/EinsteinCIReadinessCheck/home", section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Revenue Intelligence Assessor", link: "/lightning/setup/EinsteinRevIntlReadinessCheck/home", section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Sales Cloud Einstein Assessor", link: "/lightning/setup/SalesCloudEinsteinReadinessCheck/home", section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Service Cloud Einstein Assessor", link: "lightning/setup/ServiceCloudEinsteinReadinessCheck/home", section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  //Platform Tools > Einstein > Einstein Platform
  {label: "Einstein Prediction Builder", link: "/lightning/setup/EinsteinBuilder/home", section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  {label: "Einstein Recommendation Builder", link: "/lightning/setup/EinsteinRecommendation/home", section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  {label: "Einstein.ai", link: "/lightning/setup/EinsteinKeyManagement/home", section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  //Platform Tools > Einstein > Einstein Search
  {label: "Objects to Always Search", link: "/lightning/setup/SearchScope/home", section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Search Layouts", link: "/lightning/setup/EinsteinSearchLayouts/home", section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Search Manager", link: "/lightning/setup/SearchConfiguration/home", section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Settings", link: "/lightning/setup/EinsteinSearchSettings/home", section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Synonyms", link: "/lightning/setup/ManageSynonyms/home", section: "Platform Tools > Einstein > Einstein Search", prod: false},

  //Platform Tools > Feature Settings > Salesforce Files
  {label: "Asset Files", link: "/lightning/setup/ContentAssets/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Content Deliveries and Public Links", link: "/lightning/setup/ContentDistribution/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Files Connect", link: "/lightning/setup/ContentHub/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "General Settings", link: "/lightning/setup/FilesGeneralSettings/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Regenerate Previews", link: "/lightning/setup/RegeneratePreviews/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Salesforce CRM Content", link: "/lightning/setup/SalesforceCRMContent/home", section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},

  //Platform Tools > Feature Settings > Sales
  {label: "Activity Settings", link: "/lightning/setup/HomeActivitiesSetupPage/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contact Roles on Contracts", link: "/lightning/setup/ContractContactRoles/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contact Roles on Opportunities", link: "/lightning/setup/OpportunityRoles/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contract Settings", link: "/lightning/setup/ContractSettings/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Individual Settings", link: "/lightning/setup/IndividualSettings/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "LinkedIn Sales Navigator", link: "/lightning/setup/LinkedInSalesNavigatorPage/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Notes Settings", link: "/lightning/setup/NotesSetupPage/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Order Settings", link: "/lightning/setup/OrderSettings/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Sales Processes", link: "/lightning/setup/OpportunityProcess/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Social Accounts and Contacts Settings", link: "/lightning/setup/SocialProfileOrgSettings/home", section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Update Reminders", link: "/lightning/setup/OpportunityUpdateReminders/home", section: "Platform Tools > Feature Settings > Sales", prod: false},

  //Platform Tools > Feature Settings > Sales > Account
  {label: "Account Settings", link: "/lightning/setup/AccountSettings/home", section: "Platform Tools > Feature Settings > Sales > Account", prod: false},
  {label: "Account Teams", link: "/lightning/setup/AccountTeamSelling/home", section: "Platform Tools > Feature Settings > Sales > Account", prod: false},
  {label: "Person Account", link: "/lightning/setup/PersonAccountSettings/home", section: "Platform Tools > Feature Settings > Sales > Account", prod: false},

  //Platform Tools > Feature Settings > Service
  {label: "Case Assignment Rules", link: "/lightning/setup/CaseRules/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Auto-Response Rules", link: "/lightning/setup/CaseResponses/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Comment Triggers", link: "/lightning/setup/CaseCommentTriggers/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Team Roles", link: "/lightning/setup/CaseTeamRoles/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Predefined Case Teams", link: "/lightning/setup/CaseTeamTemplates/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Contact Roles on Cases", link: "/lightning/setup/CaseContactRoles/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Customer Contact Requests", link: "/lightning/setup/ContactRequestFlows/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Email-to-Case", link: "/lightning/setup/EmailToCase/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Escalation Rules", link: "/lightning/setup/CaseEscRules/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Feed Filters", link: "/lightning/setup/FeedFilterDefinitions/home", section: "Platform Tools > Feature Settings > Service", prod: false},

  //Platform Tools > Feature Settings > Service > Field Service
  {label: "Field Service Settings", link: "/lightning/setup/FieldServiceSettings/home", section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},
  {label: "Field Service Mobile App Builder", link: "/lightning/setup/FieldServiceAppBuilder/home", section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},
  {label: "Inbound Social Post Errors", link: "/lightning/setup/InboundSocialPostErrors/homee", section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},

  //Platform Tools > Feature Settings > Service > Knowledge
  {label: "Data Category Assignments", link: "/lightning/setup/KnowledgeDataCategorySetup/home", section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Data Category Mapping", link: "/lightning/setup/ArticleFilterRules/home", section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Knowledge Settings", link: "/lightning/setup/KnowledgeSettings/home", section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Validation Statuses", link: "/lightning/setup/ValidationStatuses/home", section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},

  {label: "Macro Settings", link: "/lightning/setup/MacroSettings/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Omni-Channel Settings", link: "/lightning/setup/OmniChannelSettings/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Snap-ins", link: "/lightning/setup/Snap-ins/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Social Business Rules", link: "/lightning/setup/SocialCustomerServiceBusinessRules/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Social Customer Service", link: "/lightning/setup/SocialCustomerManagementAccountSettings/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Support Processes", link: "/lightning/setup/CaseProcess/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Support Settings", link: "/lightning/setup/CaseSettings/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Web-to-Case", link: "/lightning/setup/CaseWebtocase/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Web-to-Case HTML Generator", link: "/lightning/setup/CaseWebToCaseHtmlGenerator/home", section: "Platform Tools > Feature Settings > Service", prod: false},
  //Platform Tools > Feature Settings > Survey
  {label: "Survey Settings", link: "/lightning/setup/SurveySettings/home", section: "Platform Tools > Feature Settings > Survey", prod: false},
  //Platform Tools > Objects and Fields
  {label: "Object Manager", link: "/lightning/setup/ObjectManager/home", section: "Platform Tools > Objects and Fields", prod: false},
  {label: "Picklist Value Sets", link: "/lightning/setup/Picklists/home", section: "Platform Tools > Objects and Fields", prod: false},
  {label: "Schema Builder", link: "/lightning/setup/SchemaBuilder/home", section: "Platform Tools > Objects and Fields", prod: false},
  //Platform Tools > Events
  {label: "Event Manager", link: "/lightning/setup/EventManager/home", section: "Platform Tools > Events", prod: false},
  //Platform Tools > Process Automation
  {label: "Approval Processes", link: "/lightning/setup/ApprovalProcesses/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Automation Home", link: "/lightning/setup/ProcessHome/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Flows", link: "/lightning/setup/Flows/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Migrate to Flow", link: "/lightning/setup/MigrateToFlowTool/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Next Best Action", link: "/lightning/setup/NextBestAction/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Paused And Failed Flow Interviews", link: "/lightning/setup/Pausedflows/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Post Templates", link: "/lightning/setup/FeedTemplates/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Process Automation Settings", link: "/lightning/setup/WorkflowSettings/home", section: "Platform Tools > Process Automation", prod: false},
  {label: "Process Builder", link: "/lightning/setup/ProcessAutomation/home", section: "Platform Tools > Process Automation", prod: false},

  {label: "Email Alerts", link: "/lightning/setup/WorkflowEmails/home", section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Field Updates", link: "/lightning/setup/WorkflowFieldUpdates/home", section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Outbound Messages", link: "/lightning/setup/WorkflowOutboundMessaging/home", section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Send Actions", link: "/lightning/setup/SendAction/home", section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Tasks", link: "/lightning/setup/WorkflowTasks/home", section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Workflow Rules", link: "/lightning/setup/WorkflowRules/home", section: "Platform Tools > Process Automation", prod: false},
  //User Interface
  {label: "Action Link Templates", link: "/lightning/setup/ActionLinkGroupTemplates/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Guided Actions", link: "/lightning/setup/GuidedActions/home", section: "Platform Tools > User Interface", prod: false},
  {label: "App Menu", link: "/lightning/setup/AppMenu/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Custom Labels", link: "/lightning/setup/ExternalStrings/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Density Settings", link: "/lightning/setup/DensitySetup/home", section: "Platform Tools > User Interface", prod: false},

  {label: "Global Actions", link: "/lightning/setup/GlobalActions/home", section: "Platform Tools > User Interface > Global Actions", prod: false},
  {label: "Publisher Layouts", link: "/lightning/setup/GlobalPublisherLayouts/home", section: "Platform Tools > User Interface > Global Actions", prod: false},

  {label: "Lightning App Builder", link: "/lightning/setup/FlexiPageList/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Lightning Extension", link: "/lightning/setup/LightningExtension/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Loaded Console Tab Limit", link: "/lightning/setup/ConsoleMaxTabCacheSetup/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Path Settings", link: "/lightning/setup/PathAssistantSetupHome/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Quick Text Settings", link: "/lightning/setup/LightningQuickTextSettings/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Record Page Settings", link: "/lightning/setup/SimpleRecordHome/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Rename Tabs and Labels", link: "/lightning/setup/RenameTab/home", section: "Platform Tools > User Interface", prod: false},
  //Sites and Domains
  {label: "Custom URLs", link: "/lightning/setup/DomainSites/home", section: "Platform Tools > User Interface > Sites and Domains", prod: false},
  {label: "Domains", link: "/lightning/setup/DomainNames/home", section: "Platform Tools > User Interface > Sites and Domains", prod: false},
  {label: "Sites", link: "/lightning/setup/CustomDomain/home", section: "Platform Tools > User Interface > Sites and Domains", prod: false},

  {label: "Tabs", link: "/lightning/setup/CustomTabs/home", section: "Platform Tools > User Interface", prod: false},
  {label: "Themes and Branding", link: "/lightning/setup/ThemingAndBranding/home", section: "Platform Tools > User Interface", prod: false},
  //Translation Workbench
  {label: "Data Translation Settings", link: "/lightning/setup/LabelWorkbenchDataTranslationSetup/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Export", link: "/lightning/setup/LabelWorkbenchExport/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Import", link: "/lightning/setup/LabelWorkbenchImport/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Override", link: "/lightning/setup/LabelWorkbenchOverride/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Translate", link: "/lightning/setup/LabelWorkbenchTranslate/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Translation Settings", link: "/lightning/setup/LabelWorkbenchSetup/home", section: "Platform Tools > User Interface > Translation Workbench", prod: false},

  {label: "User Interface", link: "/lightning/setup/UserInterfaceUI/home", section: "Platform Tools > User Interface", prod: false},
  //Custom Code
  {label: "Apex Classes", link: "/lightning/setup/ApexClasses/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Hammer Test Results", link: "/lightning/setup/ApexHammerResultStatus/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Settings", link: "/lightning/setup/ApexSettings/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Test Execution", link: "/lightning/setup/ApexTestQueue/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Test History", link: "/lightning/setup/ApexTestHistory/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Triggers", link: "/lightning/setup/ApexTriggers/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Canvas App Previewer", link: "/lightning/setup/CanvasPreviewerUi/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Metadata Types", link: "/lightning/setup/CustomMetadata/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Permissions", link: "/lightning/setup/CustomPermissions/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Settings", link: "/lightning/setup/CustomSettings/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Email Services", link: "/lightning/setup/EmailToApexFunction/home", section: "Platform Tools > Custom Code", prod: false},
  //Lightning Components
  {label: "Debug Mode", link: "/lightning/setup/UserDebugModeSetup/home", section: "Platform Tools > Custom Code > Lightning Components", prod: false},
  {label: "Lightning Components", link: "/lightning/setup/LightningComponentBundles/home", section: "Platform Tools > Custom Code > Lightning Components", prod: false},

  {label: "Platform Cache", link: "/lightning/setup/PlatformCache/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Remote Access", link: "/lightning/setup/RemoteAccess/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Static Resources", link: "/lightning/setup/StaticResources/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Tools", link: "/lightning/setup/ClientDevTools/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Visualforce Components", link: "/lightning/setup/ApexComponents/home", section: "Platform Tools > Custom Code", prod: false},
  {label: "Visualforce Pages", link: "/lightning/setup/ApexPages/home", section: "Platform Tools > Custom Code", prod: false},
  //Development
  {label: "Dev Hub", link: "/lightning/setup/DevHub/home", section: "Platform Tools > Dev Hub", prod: true},
  {label: "DevOps Center", link: "/lightning/setup/DevOpsCenterSetup/home", section: "Platform Tools > Dev Hub", prod: true},
  {label: "Org Shape", link: "/lightning/setup/ShapeGrantAccess/home", section: "Platform Tools > Dev Hub", prod: true},
  //Performance
  {label: "Performance Assistant", link: "/lightning/setup/PerformanceAssistant/home", section: "Platform Tools > Performance > Performance Testing", prod: false},
  //Platform Tools > Environments
  {label: "Inbound Change Sets", link: "/lightning/setup/InboundChangeSet/home", section: "Platform Tools > Environments > Change Sets", prod: false},
  {label: "Outbound Change Sets", link: "/lightning/setup/OutboundChangeSet/home", section: "Platform Tools > Environments > Change Sets", prod: false},
  //Platform Tools > Environments > Deploy
  {label: "Deployment Settings", link: "/lightning/setup/DeploymentSettings/home", section: "Platform Tools > Environments > Deploy", prod: false},
  {label: "Deployment Status", link: "/lightning/setup/DeployStatus/home", section: "Platform Tools > Environments > Deploy", prod: false},
  //Platform Tools > Environments > Jobs
  {label: "Apex Flex Queue", link: "/lightning/setup/ApexFlexQueue/home", section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Apex Jobs", link: "/lightning/setup/AsyncApexJobs/home", section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Background Jobs", link: "/lightning/setup/ParallelJobsStatus/home", section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Bulk Data Load Jobs", link: "/lightning/setup/AsyncApiJobStatus/home", section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Scheduled Jobs", link: "/lightning/setup/ScheduledJobs/home", section: "Platform Tools > Environments > Jobs", prod: false},
  //Platform Tools > Environments > Logs
  {label: "Debug Logs", link: "/lightning/setup/ApexDebugLogs/home", section: "Platform Tools > Environments > Logs", prod: false},
  {label: "Email Log Files", link: "/lightning/setup/EmailLogFiles/home", section: "Platform Tools > Environments > Logs", prod: false},
  //Platform Tools > Environments > Monitoring
  {label: "API Usage Notifications", link: "/lightning/setup/MonitoringRateLimitingNotification/home", section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Case Escalations", link: "/lightning/setup/DataManagementManageCaseEscalation/home", section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Email Snapshots", link: "/lightning/setup/EmailCapture/home", section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Outbound Messages", link: "/lightning/setup/WorkflowOmStatus/home", section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Time-Based Workflow", link: "/lightning/setup/DataManagementManageWorkflowQueue/home", section: "Platform Tools > Environments > Monitoring", prod: false},

  {label: "Sandboxes", link: "/lightning/setup/DataManagementCreateTestInstance/home", section: "Platform Tools > Environments", prod: true},
  {label: "System Overview", link: "/lightning/setup/SystemOverview/home", section: "Platform Tools > Environments", prod: false},
  //Platform Tools > User Engagement
  {label: "Adoption Assistance", link: "/lightning/setup/AdoptionAssistance/home", section: "Platform Tools > User Engagement", prod: false},
  {label: "Guidance Center", link: "/lightning/setup/LearningSetup/home", section: "Platform Tools > User Engagement", prod: false},
  {label: "Help Menu", link: "/lightning/setup/HelpMenu/home", section: "Platform Tools > User Engagement", prod: false},
  {label: "In-App Guidance", link: "/lightning/setup/Prompts/home", section: "Platform Tools > User Engagement", prod: false},
  //Platform Tools > Integrations
  {label: "API", link: "/lightning/setup/WebServices/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Basic Data Import", link: "/lightning/setup/BasicDataImport/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Change Data Capture", link: "/lightning/setup/CdcObjectEnablement/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Data Import Wizard", link: "/lightning/setup/DataManagementDataImporter/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Data Loader", link: "/lightning/setup/DataLoader/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Dataloader.io", link: "/lightning/setup/DataLoaderIo/home", section: "Platform Tools > Integrations", prod: false},
  {label: "External Data Sources", link: "/lightning/setup/ExternalDataSource/home", section: "Platform Tools > Integrations", prod: false},
  {label: "External Objects", link: "/lightning/setup/ExternalObjects/home", section: "Platform Tools > Integrations", prod: false},
  {label: "External Services", link: "/lightning/setup/ExternalServices/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Platform Events", link: "/lightning/setup/EventObjects/home", section: "Platform Tools > Integrations", prod: false},
  {label: "Teams Integration", link: "/lightning/setup/MicrosoftTeamsIntegration/home", section: "Platform Tools > Integrations", prod: false},
  //Platform Tools > Notification Builder
  {label: "Custom Notifications", link: "/lightning/setup/CustomNotifications/home", section: "Platform Tools > Notification Builder", prod: false},
  {label: "Notification Delivery Settings", link: "/lightning/setup/NotificationTypesManager/home", section: "Platform Tools > Notification Builder", prod: false},
  //Settings > Company Settings
  {label: "Business Hours", link: "/lightning/setup/BusinessHours/home", section: "Settings > Company Settings", prod: false},
  {label: "Public Calendars and Resources", link: "/lightning/setup/Calendars/home", section: "Settings > Company Settings > Calendar Settings", prod: false},
  {label: "Company Information", link: "/lightning/setup/CompanyProfileInfo/home", section: "Settings > Company Settings", prod: false},
  {label: "Data Protection and Privacy", link: "/lightning/setup/ConsentManagement/home", section: "Settings > Company Settings", prod: false},
  {label: "Fiscal Year", link: "/lightning/setup/ForecastFiscalYear/home", section: "Settings > Company Settings", prod: false},
  {label: "Holidays", link: "/lightning/setup/Holiday/home", section: "Settings > Company Settings", prod: false},
  {label: "Language Settings", link: "/lightning/setup/LanguageSettings/home", section: "Settings > Company Settings", prod: false},
  {label: "Manage Currencies", link: "/lightning/setup/CompanyCurrency/home", section: "Settings > Company Settings", prod: false},
  {label: "Maps and Location Settings", link: "/lightning/setup/MapsAndLocationServicesSettings/home", section: "Settings > Company Settings", prod: false},
  {label: "My Domain", link: "/lightning/setup/OrgDomain/home", section: "Settings > Company Settings", prod: false},
  //Settings > Data Classification
  {label: "Data Classification", link: "/lightning/setup/DataClassificationSettings/home", section: "Settings > Data Classification", prod: false},
  {label: "Data Classification Download", link: "/lightning/setup/DataClassificationDownload/home", section: "Settings > Data Classification", prod: false},
  {label: "Data Classification Upload", link: "/lightning/setup/DataClassificationUpload/home", section: "Settings > Data Classification", prod: false},
  //Settings > Privacy Center
  {label: "Consent Event Stream", link: "/lightning/setup/ConsentEventStream/home", section: "Settings > Privacy Center", prod: false},
  //Settings > Identity
  {label: "Auth. Providers", link: "/lightning/setup/AuthProviders/home", section: "Settings > Identity", prod: false},
  {label: "Identity Provider", link: "/lightning/setup/IdpPage/home", section: "Settings > Identity", prod: false},
  {label: "Identity Provider Event Log", link: "/lightning/setup/IdpErrorLog/home", section: "Settings > Identity", prod: false},
  {label: "Identity Verification", link: "/lightning/setup/IdentityVerification/home", section: "Settings > Identity", prod: false},
  {label: "Identity Verification History", link: "/lightning/setup/VerificationHistory/home", section: "Settings > Identity", prod: false},
  {label: "Login Flows", link: "/lightning/setup/LoginFlow/home", section: "Settings > Identity", prod: false},
  {label: "Login History", link: "/lightning/setup/OrgLoginHistory/home", section: "Settings > Identity", prod: false},
  {label: "OAuth Custom Scopes", link: "/lightning/setup/OauthCustomScope/home", section: "Settings > Identity", prod: false},
  {label: "OAuth and OpenID Connect Settings", link: "/lightning/setup/OauthOidcSettings/home", section: "Settings > Identity", prod: false},
  {label: "Single Sign-On Settings", link: "/lightning/setup/SingleSignOn/home", section: "Settings > Identity", prod: false},
  //Settings > Security
  {label: "Account Owner Report", link: "/lightning/setup/SecurityAccountOwner/home", section: "Settings > Security", prod: false},
  {label: "Activations", link: "/lightning/setup/ActivatedIpAddressAndClientBrowsersPage/home", section: "Settings > Security", prod: false},
  {label: "CORS", link: "/lightning/setup/CorsWhitelistEntries/home", section: "Settings > Security", prod: false},
  {label: "CSP Trusted Sites", link: "/lightning/setup/SecurityCspTrustedSite/home", section: "Settings > Security", prod: false},
  {label: "Certificate and Key Management", link: "/lightning/setup/CertificatesAndKeysManagement/home", section: "Settings > Security", prod: false},
  {label: "Delegated Administration", link: "/lightning/setup/DelegateGroups/home", section: "Settings > Security", prod: false},
  //Settings > Security > Event Monitoring
  {label: "Event Monitoring Settings", link: "/lightning/setup/EventMonitoringSetup/home", section: "Settings > Security > Event Monitoring", prod: false},
  {label: "Transaction Security Policies", link: "/lightning/setup/TransactionSecurityNew/home", section: "Settings > Security > Event Monitoring", prod: false},
  //Settings > Security
  {label: "Expire All Passwords", link: "/lightning/setup/SecurityExpirePasswords/home", section: "Settings > Security", prod: false},
  {label: "Field Accessibility", link: "/lightning/setup/FieldAccessibility/home", section: "Settings > Security", prod: false},
  {label: "File Upload and Download Security", link: "/lightning/setup/FileTypeSetting/home", section: "Settings > Security", prod: false},
  {label: "Health Check", link: "/lightning/setup/HealthCheck/home", section: "Settings > Security", prod: false},
  {label: "Login Access Policies", link: "/lightning/setup/LoginAccessPolicies/home", section: "Settings > Security", prod: false},
  {label: "Named Credentials", link: "/lightning/setup/NamedCredential/home", section: "Settings > Security", prod: false},
  {label: "Network Access", link: "/lightning/setup/NetworkAccess/home", section: "Settings > Security", prod: false},
  {label: "Password Policies", link: "/lightning/setup/SecurityPolicies/home", section: "Settings > Security", prod: false},
  //Settings > Security > Platform Encryption
  {label: "Advanced Settings", link: "/lightning/setup/SecurityRemoteProxy/home", section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Encryption Policy", link: "/lightning/setup/EncryptionPolicy/home", section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Encryption Statistics", link: "/lightning/setup/EncryptionStatistics/home", section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Key Management", link: "/lightning/setup/PlatformEncryptionKeyManagement/home", section: "Settings > Security > Platform Encryption", prod: false},
  //Settings > Security
  {label: "Portal Health Check", link: "/lightning/setup/PortalSecurityReport/home", section: "Settings > Security", prod: false},
  {label: "Private Connect", link: "/lightning/setup/PrivateConnect/home", section: "Settings > Security", prod: false},
  {label: "Remote Site Settings", link: "/lightning/setup/SecurityRemoteProxy/home", section: "Settings > Security", prod: false},
  {label: "Session Management", link: "/lightning/setup/SessionManagementPage/home", section: "Settings > Security", prod: false},
  {label: "Session Settings", link: "/lightning/setup/SecuritySession/home", section: "Settings > Security", prod: false},
  {label: "Sharing Settings", link: "/lightning/setup/SecuritySharing/home", section: "Settings > Security", prod: false},
  {label: "Trusted URLs for Redirects", link: "/lightning/setup/SecurityRedirectWhitelistUrl/home", section: "Settings > Security", prod: false},
  {label: "View Setup Audit Trail", link: "/lightning/setup/SecurityEvents/home", section: "Settings > Security", prod: false},

  //Custom Link:
  {label: "Create New Flow", link: "/builder_platform_interaction/flowBuilder.app", section: "Platform Tools > Objects and Fields > New", prod: false},
  {label: "Create New Custom Object", link: "/lightning/setup/ObjectManager/new", section: "Platform Tools > Process Automation", prod: false},
  {label: "Create New Permission Set", link: "/lightning/setup/PermSets/page?address=/udd/PermissionSet/newPermissionSet.apexp", section: "Administration > Users > Permission Set", prod: false},
  {label: "Create New Custom Permission", link: "/lightning/setup/CustomPermissions/page?address=/0CP/e", section: "Platform Tools > Custom Code > Custom Permission", prod: false},
  {label: "Recycle Bin", link: "/lightning/o/DeleteEvent/home", section: "App Launcher > Custom Link", prod: false},

  //ConnectApi namespace classes doc links
  {label: "Class ActionLinks", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ActionLinks_static_methods.htm", section: "Documentation Apex> ConnectApi > ActionLinks", prod: false, isExternal: true},
  {label: "Class Announcements", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Announcements_static_methods.htm", section: "Documentation Apex> ConnectApi > Announcements", prod: false, isExternal: true},
  {label: "Class BotVersionActivation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_BotVersionActivation_static_methods.htm", section: "Documentation Apex> ConnectApi > BotVersionActivation", prod: false, isExternal: true},
  {label: "Class CdpCalculatedInsight", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpCalculatedInsight_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpCalculatedInsight", prod: false, isExternal: true},
  {label: "Class CdpIdentityResolution", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpIdentityResolution_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpIdentityResolution", prod: false, isExternal: true},
  {label: "Class CdpQuery", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpQuery_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpQuery", prod: false, isExternal: true},
  {label: "Class CdpSegment", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CdpSegment_static_methods.htm", section: "Documentation Apex> ConnectApi > CdpSegment", prod: false, isExternal: true},
  {label: "Class Chatter", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Chatter_static_methods.htm", section: "Documentation Apex> ConnectApi > Chatter", prod: false, isExternal: true},
  {label: "Class ChatterFavorites", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterFavorites_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterFavorites", prod: false, isExternal: true},
  {label: "Class ChatterFeeds", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterFeeds_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterFeeds", prod: false, isExternal: true},
  {label: "Class ChatterGroups", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterGroups_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterGroups", prod: false, isExternal: true},
  {label: "Class ChatterMessages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterMessages_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterMessages", prod: false, isExternal: true},
  {label: "Class ChatterUsers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ChatterUsers_static_methods.htm", section: "Documentation Apex> ConnectApi > ChatterUsers", prod: false, isExternal: true},
  {label: "Class Clm", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Clm_static_methods.htm", section: "Documentation Apex> ConnectApi > Clm", prod: false, isExternal: true},
  {label: "Class CommerceBuyerExperience", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceBuyerExperience_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceBuyerExperience", prod: false, isExternal: true},
  {label: "Class CommerceCart", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceCart_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceCart", prod: false, isExternal: true},
  {label: "Class CommerceCatalog", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceCatalog_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceCatalog", prod: false, isExternal: true},
  {label: "Class CommercePromotions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommercePromotions_static_methods.htm", section: "Documentation Apex> ConnectApi > CommercePromotions", prod: false, isExternal: true},
  {label: "Class CommerceSearch", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearch_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearch", prod: false, isExternal: true},
  {label: "Class CommerceSearchConnectFamily", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearchConnectFamily_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearchConnectFamily", prod: false, isExternal: true},
  {label: "Class CommerceSearchSettings", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceSearchSettings_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceSearchSettings", prod: false, isExternal: true},
  {label: "Class CommerceStorePricing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceStorePricing_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceStorePricing", prod: false, isExternal: true},
  {label: "Class CommerceWishlist", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommerceWishlist_static_methods.htm", section: "Documentation Apex> ConnectApi > CommerceWishlist", prod: false, isExternal: true},
  {label: "Class Communities", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Communities_static_methods.htm", section: "Documentation Apex> ConnectApi > Communities", prod: false, isExternal: true},
  {label: "Class CommunityModeration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_CommunityModeration_static_methods.htm", section: "Documentation Apex> ConnectApi > CommunityModeration", prod: false, isExternal: true},
  {label: "Class ContentHub", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ContentHub_static_methods.htm", section: "Documentation Apex> ConnectApi > ContentHub", prod: false, isExternal: true},
  {label: "Class ConversationApplicationDefinition", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ConversationApplicationDefinition_static_methods.htm", section: "Documentation Apex> ConnectApi > ConversationApplicationDefinition", prod: false, isExternal: true},
  {label: "Class Datacloud", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Datacloud_static_methods.htm", section: "Documentation Apex> ConnectApi > Datacloud", prod: false, isExternal: true},
  {label: "Class EmailMergeFieldService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_EmailMergeFieldService_static_methods.htm", section: "Documentation Apex> ConnectApi > EmailMergeFieldService", prod: false, isExternal: true},
  {label: "Class EmployeeProfiles", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_EmployeeProfiles_static_methods.htm", section: "Documentation Apex> ConnectApi > EmployeeProfiles", prod: false, isExternal: true},
  {label: "Class ExternalEmailServices", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ExternalEmailService_static_methods.htm", section: "Documentation Apex> ConnectApi > ExternalEmailServices", prod: false, isExternal: true},
  {label: "Class ExternalManagedAccount", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ExternalManagedAccount_static_methods.htm", section: "Documentation Apex> ConnectApi > ExternalManagedAccount", prod: false, isExternal: true},
  {label: "Class FieldService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_FieldService_static_methods.htm", section: "Documentation Apex> ConnectApi > FieldService", prod: false, isExternal: true},
  {label: "Class FulfillmentOrder", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_FulfillmentOrder_static_methods.htm", section: "Documentation Apex> ConnectApi > FulfillmentOrder", prod: false, isExternal: true},
  {label: "Class Knowledge", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Knowledge_static_methods.htm", section: "Documentation Apex> ConnectApi > Knowledge", prod: false, isExternal: true},
  {label: "Class LightningScheduler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_LightningScheduler_static_methods.htm", section: "Documentation Apex> ConnectApi > LightningScheduler", prod: false, isExternal: true},
  {label: "Class ManagedContent", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ManagedContent_static_methods.htm", section: "Documentation Apex> ConnectApi > ManagedContent", prod: false, isExternal: true},
  {label: "Class ManagedContentDelivery", link: "", section: "Documentation Apex> ConnectApi > ManagedContentDelivery", prod: false, isExternal: true},
  {label: "Class ManagedTopics", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ManagedTopics_static_methods.htm", section: "Documentation Apex> ConnectApi > ManagedTopics", prod: false, isExternal: true},
  {label: "Class MarketingIntegration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_MarketingIntegration_static_methods.htm", section: "Documentation Apex> ConnectApi > MarketingIntegration", prod: false, isExternal: true},
  {label: "Class Mentions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Mentions_static_methods.htm", section: "Documentation Apex> ConnectApi > Mentions", prod: false, isExternal: true},
  {label: "Class Missions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Missions_static_methods.htm", section: "Documentation Apex> ConnectApi > Missions", prod: false, isExternal: true},
  {label: "Class NamedCredentials", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NamedCredentials_static_methods.htm", section: "Documentation Apex> ConnectApi > NamedCredentials", prod: false, isExternal: true},
  {label: "Class NavigationMenu", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NavigationMenu_static_methods.htm", section: "Documentation Apex> ConnectApi > NavigationMenu", prod: false, isExternal: true},
  {label: "Class NextBestAction", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_NextBestAction_static_methods.htm", section: "Documentation Apex> ConnectApi > NextBestAction", prod: false, isExternal: true},
  {label: "Class OmnichannelInventoryService", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OmnichannelInventoryService_static_methods.htm", section: "Documentation Apex> ConnectApi > OmnichannelInventoryService", prod: false, isExternal: true},
  {label: "Class Orchestration", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Orchestration_static_methods.htm", section: "Documentation Apex> ConnectApi > Orchestration", prod: false, isExternal: true},
  {label: "Class OrderPaymentSummary", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderPaymentSummary_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderPaymentSummary", prod: false, isExternal: true},
  {label: "Class OrderSummary", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderSummary_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderSummary", prod: false, isExternal: true},
  {label: "Class OrderSummaryCreation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_OrderSummaryCreation_static_methods.htm", section: "Documentation Apex> ConnectApi > OrderSummaryCreation", prod: false, isExternal: true},
  {label: "Class Organization", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Organization_static_methods.htm", section: "Documentation Apex> ConnectApi > Organization", prod: false, isExternal: true},
  {label: "Class PardotBusinessUnitContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_PardotBusinessUnitContext_static_methods.htm", section: "Documentation Apex> ConnectApi > PardotBusinessUnitContext", prod: false, isExternal: true},
  {label: "Class Payments", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Payments_static_methods.htm", section: "Documentation Apex> ConnectApi > Payments", prod: false, isExternal: true},
  {label: "Class Personalization", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Personalization_static_methods.htm", section: "Documentation Apex> ConnectApi > Personalization", prod: false, isExternal: true},
  {label: "Class PickTicket", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_PickTicket_static_methods.htm", section: "Documentation Apex> ConnectApi > PickTicket", prod: false, isExternal: true},
  {label: "Class QuestionAndAnswers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_QuestionAndAnswers_static_methods.htm", section: "Documentation Apex> ConnectApi > QuestionAndAnswers", prod: false, isExternal: true},
  {label: "Class Recommendations", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Recommendations_static_methods.htm", section: "Documentation Apex> ConnectApi > Recommendations", prod: false, isExternal: true},
  {label: "Class Records", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Records_static_methods.htm", section: "Documentation Apex> ConnectApi > Records", prod: false, isExternal: true},
  {label: "Class Repricing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Repricing_static_methods.htm", section: "Documentation Apex> ConnectApi > Repricing", prod: false, isExternal: true},
  {label: "Class ReturnOrder", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_ReturnOrder_static_methods.htm", section: "Documentation Apex> ConnectApi > ReturnOrder", prod: false, isExternal: true},
  {label: "Class Routing", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Routing_static_methods.htm", section: "Documentation Apex> ConnectApi > Routing", prod: false, isExternal: true},
  {label: "Class SalesforceInbox", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_SalesforceInbox_static_methods.htm", section: "Documentation Apex> ConnectApi > SalesforceInbox", prod: false, isExternal: true},
  {label: "Class Sites", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Sites_static_methods.htm", section: "Documentation Apex> ConnectApi > Sites", prod: false, isExternal: true},
  {label: "Class SocialEngagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_SocialEngagement_static_methods.htm", section: "Documentation Apex> ConnectApi > SocialEngagement", prod: false, isExternal: true},
  {label: "Class Surveys", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Survey_static_methods.htm", section: "Documentation Apex> ConnectApi > Surveys", prod: false, isExternal: true},
  {label: "Class TaxPlatform", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_TaxPlatform_static_methods.htm", section: "Documentation Apex> ConnectApi > TaxPlatform", prod: false, isExternal: true},
  {label: "Class Topics", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Topics_static_methods.htm", section: "Documentation Apex> ConnectApi > Topics", prod: false, isExternal: true},
  {label: "Class UserProfiles", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_UserProfiles_static_methods.htm", section: "Documentation Apex> ConnectApi > UserProfiles", prod: false, isExternal: true},
  {label: "Class Zones", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Zones_static_methods.htm", section: "Documentation Apex> ConnectApi > Zones", prod: false, isExternal: true},
  {label: "Class ConnectApi Input", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_connectapi_input.htm", section: "Documentation Apex> ConnectApi > ActionLinks", prod: false, isExternal: true},
  {label: "Class ConnectApi Output", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_connectapi_output.htm", section: "Documentation Apex> ConnectApi > ConnectApi Output", prod: false, isExternal: true},
  //Database namespace classes doc links
  {label: "Class Batchable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_database_batchable.htm", section: "Documentation Apex> Database > Batchable", prod: false, isExternal: true},
  {label: "Class BatchableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_database_batchablecontext.htm", section: "Documentation Apex> Database > BatchableContext", prod: false, isExternal: true},
  {label: "Class DeletedRecord", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_deletedrecord.htm", section: "Documentation Apex> Database > DeletedRecord", prod: false, isExternal: true},
  {label: "Class DeleteResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_deleteresult.htm", section: "Documentation Apex> Database > DeleteResult", prod: false, isExternal: true},
  {label: "Class DMLOptions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_dmloptions.htm", section: "Documentation Apex> Database > DMLOptions", prod: false, isExternal: true},
  {label: "Class DuplicateError", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Database_DuplicateError.htm", section: "Documentation Apex> Database > DuplicateError", prod: false, isExternal: true},
  {label: "Class EmptyRecycleBinResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_EmptyRecycleBinResult.htm", section: "Documentation Apex> Database > EmptyRecycleBinResult", prod: false, isExternal: true},
  {label: "Class Error", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_error.htm", section: "Documentation Apex> Database > Error", prod: false, isExternal: true},
  {label: "Class GetDeletedResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_getdeletedresult.htm", section: "Documentation Apex> Database > GetDeletedResult", prod: false, isExternal: true},
  {label: "Class GetUpdatedResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_getupdatedresult.htm", section: "Documentation Apex> Database > GetUpdatedResult", prod: false, isExternal: true},
  {label: "Class LeadConvert", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_dml_convertLead.htm", section: "Documentation Apex> Database > LeadConvert", prod: false, isExternal: true},
  {label: "Class LeadConvertResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_leadconvertresult.htm", section: "Documentation Apex> Database > LeadConvertResult", prod: false, isExternal: true},
  {label: "Class MergeResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_mergeresult.htm", section: "Documentation Apex> Database > MergeResult", prod: false, isExternal: true},
  {label: "Class QueryLocator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_batch.htm", section: "Documentation Apex> Database > QueryLocator", prod: false, isExternal: true},
  {label: "Class QueryLocatorIterator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_database_querylocatoriterator.htm", section: "Documentation Apex> Database > QueryLocatorIterator", prod: false, isExternal: true},
  {label: "Class SaveResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_saveresult.htm", section: "Documentation Apex> Database > SaveResult", prod: false, isExternal: true},
  {label: "Class UndeleteResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_undeleteresult.htm", section: "Documentation Apex> Database > UndeleteResult", prod: false, isExternal: true},
  {label: "Class UpsertResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_upsertresult.htm", section: "Documentation Apex> Database > UpsertResult", prod: false, isExternal: true},
  //System namespace classes doc links
  {label: "Class AccessLevel", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AccessLevel.htm", section: "Documentation Apex> System > AccessLevel", prod: false, isExternal: true},
  {label: "Class Address", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Address.htm", section: "Documentation Apex> System > Address", prod: false, isExternal: true},
  {label: "Class Answers", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_answers.htm", section: "Documentation Apex> System > Answers", prod: false, isExternal: true},
  {label: "Class ApexPages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_apexpages.htm", section: "Documentation Apex> System > ApexPages", prod: false, isExternal: true},
  {label: "Class Approval", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_approval.htm", section: "Documentation Apex> System > Approval", prod: false, isExternal: true},
  {label: "Class Assert", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Assert.htm", section: "Documentation Apex> System > Assert", prod: false, isExternal: true},
  {label: "Class AsyncInfo", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AsyncInfo.htm", section: "Documentation Apex> System > AsyncInfo", prod: false, isExternal: true},
  {label: "Class AsyncOptions", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_AsyncOptions.htm", section: "Documentation Apex> System > AsyncOptions", prod: false, isExternal: true},
  {label: "Class Blob", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_blob.htm", section: "Documentation Apex> System > Blob", prod: false, isExternal: true},
  {label: "Class Boolean", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_boolean.htm", section: "Documentation Apex> System > Boolean", prod: false, isExternal: true},
  {label: "Class BusinessHours", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_businesshours.htm", section: "Documentation Apex> System > BusinessHours", prod: false, isExternal: true},
  {label: "Class Callable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_Callable.htm", section: "Documentation Apex> System > Callable", prod: false, isExternal: true},
  {label: "Class Cases", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_System_Cases_methods.htm", section: "Documentation Apex> System > Cases", prod: false, isExternal: true},
  {label: "Class Collator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Collator.htm", section: "Documentation Apex> System > Collator", prod: false, isExternal: true},
  {label: "Class Comparable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_comparable.htm", section: "Documentation Apex> System > Comparable", prod: false, isExternal: true},
  {label: "Class Comparator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_Comparator.htm", section: "Documentation Apex> System > Comparator", prod: false, isExternal: true},
  {label: "Class Continuation", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Continuation.htm", section: "Documentation Apex> System > Continuation", prod: false, isExternal: true},
  {label: "Class Cookie", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_sites_cookie.htm", section: "Documentation Apex> System > Cookie", prod: false, isExternal: true},
  {label: "Class Crypto", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_crypto.htm", section: "Documentation Apex> System > Crypto", prod: false, isExternal: true},
  {label: "Class Custom Metadata Type", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm", section: "Documentation Apex> System > Custom Metadata Type", prod: false, isExternal: true},
  {label: "Class Custom Settings", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_settings.htm", section: "Documentation Apex> System > Custom Settings", prod: false, isExternal: true},
  {label: "Class Database", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database.htm", section: "Documentation Apex> System > Database", prod: false, isExternal: true},
  {label: "Class Date", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_date.htm", section: "Documentation Apex> System > Date", prod: false, isExternal: true},
  {label: "Class Datetime", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_datetime.htm", section: "Documentation Apex> System > Datetime", prod: false, isExternal: true},
  {label: "Class Decimal", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_decimal.htm", section: "Documentation Apex> System > Decimal", prod: false, isExternal: true},
  {label: "Class Domain", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Domain.htm", section: "Documentation Apex> System > Domain", prod: false, isExternal: true},
  {label: "Class DomainCreator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_DomainCreator.htm", section: "Documentation Apex> System > DomainCreator", prod: false, isExternal: true},
  {label: "Class DomainParser", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_DomainParser.htm", section: "Documentation Apex> System > DomainParser", prod: false, isExternal: true},
  {label: "Class Double", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_double.htm", section: "Documentation Apex> System > Double", prod: false, isExternal: true},
  {label: "Class EmailMessages", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_emailmessages.htm", section: "Documentation Apex> System > EmailMessages", prod: false, isExternal: true},
  {label: "Class EncodingUtil", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_encodingUtil.htm", section: "Documentation Apex> System > EncodingUtil", prod: false, isExternal: true},
  {label: "Class EventBus", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_eventbus.htm", section: "Documentation Apex> System > EventBus", prod: false, isExternal: true},
  {label: "Class FlexQueue", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FlexQueue.htm", section: "Documentation Apex> System > FlexQueue", prod: false, isExternal: true},
  {label: "Class FeatureManagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FeatureManagement.htm", section: "Documentation Apex> System > FeatureManagement", prod: false, isExternal: true},
  {label: "Class Formula", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Formula.htm", section: "Documentation Apex> System > Formula", prod: false, isExternal: true},
  {label: "Class FormulaRecalcFieldError", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FormulaRecalcFieldError.htm", section: "Documentation Apex> System > FormulaRecalcFieldError", prod: false, isExternal: true},
  {label: "Class FormulaRecalcResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_FormulaRecalcResult.htm", section: "Documentation Apex> System > FormulaRecalcResult", prod: false, isExternal: true},
  {label: "Class Http", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_http.htm", section: "Documentation Apex> System > Http", prod: false, isExternal: true},
  {label: "Class HttpCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_httpcalloutmock.htm", section: "Documentation Apex> System > HttpCalloutMock", prod: false, isExternal: true},
  {label: "Class HttpRequest", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_httprequest.htm", section: "Documentation Apex> System > HttpRequest", prod: false, isExternal: true},
  {label: "Class HttpResponse", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_restful_http_httpresponse.htm", section: "Documentation Apex> System > HttpResponse", prod: false, isExternal: true},
  {label: "Class Id", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_id.htm", section: "Documentation Apex> System > Id", prod: false, isExternal: true},
  {label: "Class Ideas", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_ideas.htm", section: "Documentation Apex> System > Ideas", prod: false, isExternal: true},
  {label: "Class InstallHandler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_install_handler.htm", section: "Documentation Apex> System > InstallHandler", prod: false, isExternal: true},
  {label: "Class Integer", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_integer.htm", section: "Documentation Apex> System > Integer", prod: false, isExternal: true},
  {label: "Class JSON", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Json.htm", section: "Documentation Apex> System > JSON", prod: false, isExternal: true},
  {label: "Class JSONGenerator", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_JsonGenerator.htm", section: "Documentation Apex> System > JSONGenerator", prod: false, isExternal: true},
  {label: "Class JSONParser", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_JsonParser.htm", section: "Documentation Apex> System > JSONParser", prod: false, isExternal: true},
  {label: "Class Label", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Label.htm", section: "Documentation Apex> System > Label", prod: false, isExternal: true},
  {label: "Class Limits", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm", section: "Documentation Apex> System > Limits", prod: false, isExternal: true},
  {label: "Class List", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_list.htm", section: "Documentation Apex> System > List", prod: false, isExternal: true},
  {label: "Class Location", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Location.htm", section: "Documentation Apex> System > Location", prod: false, isExternal: true},
  {label: "Class Long", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_long.htm", section: "Documentation Apex> System > Long", prod: false, isExternal: true},
  {label: "Class Map", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_map.htm", section: "Documentation Apex> System > Map", prod: false, isExternal: true},
  {label: "Class Matcher", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_pattern_and_matcher_matcher_methods.htm", section: "Documentation Apex> System > Matcher", prod: false, isExternal: true},
  {label: "Class Math", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_math.htm", section: "Documentation Apex> System > Math", prod: false, isExternal: true},
  {label: "Class Messaging", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_email_outbound_messaging.htm", section: "Documentation Apex> System > Messaging", prod: false, isExternal: true},
  {label: "Class MultiStaticResourceCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_multistaticresourcecalloutmock.htm", section: "Documentation Apex> System > MultiStaticResourceCalloutMock", prod: false, isExternal: true},
  {label: "Class Network", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_network.htm", section: "Documentation Apex> System > Network", prod: false, isExternal: true},
  {label: "Class OrgLimit", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimit.htm", section: "Documentation Apex> System > OrgLimit", prod: false, isExternal: true},
  {label: "Class OrgLimits", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimits.htm", section: "Documentation Apex> System > OrgLimits", prod: false, isExternal: true},
  {label: "Class PageReference", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_system_pagereference.htm", section: "Documentation Apex> System > PageReference", prod: false, isExternal: true},
  {label: "Class Packaging", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_Packaging.htm", section: "Documentation Apex> System > Packaging", prod: false, isExternal: true},
  {label: "Class Pattern", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_pattern_and_matcher_pattern_methods.htm", section: "Documentation Apex> System > Pattern", prod: false, isExternal: true},
  {label: "Class Queueable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Queueable.htm", section: "Documentation Apex> System > Queueable", prod: false, isExternal: true},
  {label: "Class QueueableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_queueablecontext.htm", section: "Documentation Apex> System > QueueableContext", prod: false, isExternal: true},
  {label: "Class QueueableDuplicateSignature", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_QueueableDuplicateSignature.htm", section: "Documentation Apex> System > QueueableDuplicateSignature", prod: false, isExternal: true},
  {label: "Class QuickAction", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_quickaction.htm", section: "Documentation Apex> System > QuickAction", prod: false, isExternal: true},
  {label: "Class RemoteObjectController", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_system_remoteobjectcontroller.htm", section: "Documentation Apex> System > RemoteObjectController", prod: false, isExternal: true},
  {label: "Class Request", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Request.htm", section: "Documentation Apex> System > Request", prod: false, isExternal: true},
  {label: "Class ResetPasswordResult", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_ResetPasswordResult.htm", section: "Documentation Apex> System > ResetPasswordResult", prod: false, isExternal: true},
  {label: "Class RestContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restcontext.htm", section: "Documentation Apex> System > RestContext", prod: false, isExternal: true},
  {label: "Class RestRequest", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restrequest.htm", section: "Documentation Apex> System > RestRequest", prod: false, isExternal: true},
  {label: "Class RestResponse", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_restresponse.htm", section: "Documentation Apex> System > RestResponse", prod: false, isExternal: true},
  {label: "Class SandboxPostCopy", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_SandboxPostCopy.htm", section: "Documentation Apex> System > SandboxPostCopy", prod: false, isExternal: true},
  {label: "Class Schedulable", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_schedulable.htm", section: "Documentation Apex> System > Schedulable", prod: false, isExternal: true},
  {label: "Class SchedulableContext", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_system_schedulablecontext.htm", section: "Documentation Apex> System > SchedulableContext", prod: false, isExternal: true},
  {label: "Class Schema", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_schema.htm", section: "Documentation Apex> System > Schema", prod: false, isExternal: true},
  {label: "Class Search", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_search.htm", section: "Documentation Apex> System > Search", prod: false, isExternal: true},
  {label: "Class Security", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_Security.htm", section: "Documentation Apex> System > Security", prod: false, isExternal: true},
  {label: "Class SelectOption", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_pages_selectoption.htm", section: "Documentation Apex> System > SelectOption", prod: false, isExternal: true},
  {label: "Class Set", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_set.htm", section: "Documentation Apex> System > Set", prod: false, isExternal: true},
  {label: "Class Site", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_sites.htm", section: "Documentation Apex> System > Site", prod: false, isExternal: true},
  {label: "Class SObject", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_sobject.htm", section: "Documentation Apex> System > SObject", prod: false, isExternal: true},
  {label: "Class SObjectAccessDecision", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_SObjectAccessDecision.htm", section: "Documentation Apex> System > SObjectAccessDecision", prod: false, isExternal: true},
  {label: "Class StaticResourceCalloutMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_staticresourcecalloutmock.htm", section: "Documentation Apex> System > StaticResourceCalloutMock", prod: false, isExternal: true},
  {label: "Class String", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_string.htm", section: "Documentation Apex> System > String", prod: false, isExternal: true},
  {label: "Class StubProvider", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_System_StubProvider.htm", section: "Documentation Apex> System > StubProvider", prod: false, isExternal: true},
  {label: "Class System", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_system.htm", section: "Documentation Apex> System > System", prod: false, isExternal: true},
  {label: "Class Test", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_test.htm", section: "Documentation Apex> System > Test", prod: false, isExternal: true},
  {label: "Class Time", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_time.htm", section: "Documentation Apex> System > Time", prod: false, isExternal: true},
  {label: "Class TimeZone", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_timezone.htm", section: "Documentation Apex> System > TimeZone", prod: false, isExternal: true},
  {label: "Class Type", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_type.htm", section: "Documentation Apex> System > Type", prod: false, isExternal: true},
  {label: "Class UninstallHandler", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_uninstall_handler.htm", section: "Documentation Apex> System > UninstallHandler", prod: false, isExternal: true},
  {label: "Class URL", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_url.htm", section: "Documentation Apex> System > URL", prod: false, isExternal: true},
  {label: "Class UserInfo", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_userinfo.htm", section: "Documentation Apex> System > UserInfo", prod: false, isExternal: true},
  {label: "Class UserManagement", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_UserManagement.htm", section: "Documentation Apex> System > UserManagement", prod: false, isExternal: true},
  {label: "Class Version", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_version.htm", section: "Documentation Apex> System > Version", prod: false, isExternal: true},
  {label: "Class WebServiceCallout", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_WebServiceCallout.htm", section: "Documentation Apex> System > WebServiceCallout", prod: false, isExternal: true},
  {label: "Class WebServiceMock", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_interface_webservicemock.htm", section: "Documentation Apex> System > WebServiceMock", prod: false, isExternal: true},
  {label: "Class XmlStreamReader", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_xml_XmlStream_reader.htm", section: "Documentation Apex> System > XmlStreamReader", prod: false, isExternal: true},
  {label: "Class XmlStreamWriter", link: "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_xml_XmlStream_writer.htm", section: "Documentation Apex> System > XmlStreamWriter", prod: false, isExternal: true},
  {label: "Class Boolean", link: "", section: "Documentation Apex> System > String", prod: false, isExternal: true}
];
