const setup = "/lightning/setup";
const apexref = "https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/";


export const setupLinks = [
  //Setup
  {label: "Setup Home", link: `${setup}/SetupOneHome/home`, section: "Setup", prod: false},
  {label: "Service Setup Assistant", link: `${setup}/ServiceHome/home`, section: "Setup", prod: false},
  {label: "Service Setup", link: `${setup}/SetupOneHome/home`, section: "Setup", prod: false},
  {label: "Multi-Factor Authentication Assistant", link: `${setup}/MfaAssistant/home`, section: "Setup", prod: false},
  {label: "Release Updates", link: `${setup}/ReleaseUpdates/home`, section: "Setup", prod: false},
  {label: "Salesforce Mobile App", link: `${setup}/SalesforceMobileAppQuickStart/home`, section: "Setup", prod: false},
  {label: "Optimizer", link: `${setup}/SalesforceOptimizer/home`, section: "Setup", prod: false},

  //Administration > Users
  {label: "Permission Sets Groups", link: `${setup}/PermSetGroups/home`, section: "Administration > Users", prod: false},
  {label: "Permission Sets", link: `${setup}/PermSets/home`, section: "Administration > Users", prod: false},
  {label: "Profiles", link: `${setup}/Profiles/home`, section: "Administration > Users", prod: false},
  {label: "Profiles (Enhanced)", link: `${setup}/EnhancedProfiles/home`, section: "Administration > Users", prod: false},
  {label: "Public Groups", link: `${setup}/PublicGroups/home`, section: "Administration > Users", prod: false},
  {label: "Queues", link: `${setup}/Queues/home`, section: "Administration > Users", prod: false},
  {label: "Roles", link: `${setup}/Roles/home`, section: "Administration > Users", prod: false},
  {label: "User Management Settings", link: `${setup}/UserManagementSettings/home`, section: "Administration > Users", prod: false},
  {label: "Users", link: `${setup}/ManageUsers/home`, section: "Administration > Users", prod: false},
  //Administration > Data
  {label: "Big Objects", link: `${setup}/BigObjects/home`, section: "Administration > Data", prod: false},
  {label: "Data Export", link: `${setup}/DataManagementExport/home`, section: "Administration > Data", prod: false},
  {label: "Data Integration Metrics", link: `${setup}/XCleanVitalsUi/home`, section: "Administration > Data", prod: false},
  {label: "Data Integration Rules", link: `${setup}/CleanRules/home`, section: "Administration > Data", prod: false},
  //Administration > Data > Duplicate Management
  {label: "Duplicate Error Logs", link: `${setup}/DuplicateErrorLog/home`, section: "Administration > Data > Duplicate Management", prod: false},
  {label: "Duplicate Rules", link: `${setup}/DuplicateRules/home`, section: "Administration > Data > Duplicate Management", prod: false},
  {label: "Matching Rules", link: `${setup}/MatchingRules/home`, section: "Administration > Data > Duplicate Management", prod: false},
  //Administration > Data
  {label: "Mass Delete Records", link: `${setup}/DataManagementDelete/home`, section: "Administration > Data", prod: false},
  {label: "Mass Transfer Approval Requests", link: `${setup}/DataManagementManageApprovals/home`, section: "Administration > Data", prod: false},
  {label: "Mass Transfer Records", link: `${setup}/DataManagementTransfer/home`, section: "Administration > Data", prod: false},
  {label: "Mass Update Addresses", link: `${setup}/DataManagementMassUpdateAddresses/home`, section: "Administration > Data", prod: false},
  {label: "Picklist Settings", link: `${setup}/PicklistSettings/home`, section: "Administration > Data", prod: false},
  {label: "Schema Settings", link: `${setup}/SchemaSettings/home`, section: "Administration > Data", prod: false},
  {label: "State and Country/Territory Picklists", link: `${setup}/AddressCleanerOverview/home`, section: "Administration > Data", prod: false},
  {label: "Storage Usage", link: `${setup}/CompanyResourceDisk/home`, section: "Administration > Data", prod: false},
  //Administration > Email
  {label: "Apex Exception Email", link: `${setup}/ApexExceptionEmail/home`, section: "Administration > Email", prod: false},
  {label: "Classic Email Templates", link: `${setup}/CommunicationTemplatesEmail/home`, section: "Administration > Email", prod: false},
  {label: "Compliance BCC Email", link: `${setup}/SecurityComplianceBcc/home`, section: "Administration > Email", prod: false},
  {label: "DKIM Keys", link: `${setup}/EmailDKIMList/home`, section: "Administration > Email", prod: false},
  {label: "Deliverability", link: `${setup}/OrgEmailSettings/home`, section: "Administration > Email", prod: false},
  {label: "Email Attachments", link: `${setup}/EmailAttachmentSettings/home`, section: "Administration > Email", prod: false},
  //Administration > Email > Delivery Settings
  {label: "Email Domain Filters", link: `${setup}/EmailDomainFilter/home`, section: "Administration > Email > Delivery Settings", prod: false},
  {label: "Email Relays", link: `${setup}/EmailRelay/home`, section: "Administration > Email > Delivery Settings", prod: false},
  //Administration >Email
  {label: "Email Footers", link: `${setup}/EmailDisclaimers/home`, section: "Administration > Email", prod: false},
  {label: "Email to Salesforce", link: `${setup}/EmailToSalesforce/home`, section: "Administration > Email", prod: false},
  {label: "Enhanced Email", link: `${setup}/EnhancedEmail/home`, section: "Administration > Email", prod: false},
  {label: "Gmail Integration and Sync", link: `${setup}/LightningForGmailAndSyncSettings/home`, section: "Administration > Email", prod: false},
  {label: "Letterheads", link: `${setup}/CommunicationTemplatesLetterheads/home`, section: "Administration > Email", prod: false},
  {label: "Lightning Email Templates", link: `${setup}/LightningEmailTemplateSetup/home`, section: "Administration > Email", prod: false},
  {label: "Mail Merge Templates", link: `${setup}/CommunicationTemplatesWord/home`, section: "Administration > Email", prod: false},
  {label: "Organization-Wide Addresses", link: `${setup}/OrgWideEmailAddresses/home`, section: "Administration > Email", prod: false},
  {label: "Outlook Configurations", link: `${setup}/EmailConfigurations/home`, section: "Administration > Email", prod: false},
  {label: "Outlook Integration and Sync", link: `${setup}/LightningForOutlookAndSyncSettings/home`, section: "Administration > Email", prod: false},
  {label: "Send through External Email Services", link: `${setup}/EmailTransportServiceSetupPage/home`, section: "Administration > Email", prod: false},
  {label: "Test Deliverability", link: `${setup}/TestEmailDeliverability/home`, section: "Administration > Email", prod: false},

  //Platform Tools > Apps
  {label: "App Manager", link: `${setup}/NavigationMenus/home`, section: "Platform Tools > Apps", prod: false},
  {label: "AppExchange Marketplace", link: `${setup}/AppExchangeMarketplace/home`, section: "Platform Tools > Apps", prod: false},
  //Platform Tools > Apps > Connected Apps
  {label: "Connected Apps OAuth Usage", link: `${setup}/ConnectedAppsUsage/home`, section: "Platform Tools > Apps > Connected Apps", prod: false},
  {label: "Manage Connected Apps", link: `${setup}/ConnectedApplication/home`, section: "Platform Tools > Apps > Connected Apps", prod: false},
  //Platform Tools > Apps > Lightning Bolt
  {label: "Flow Category", link: `${setup}/FlowCategory/home`, section: "Platform Tools > Apps > Lightning Bolt", prod: false},
  {label: "Lightning Bolt Solutions", link: `${setup}/LightningBolt/home`, section: "Platform Tools > Apps > Lightning Bolt", prod: false},
  //Platform Tools > Apps > Mobile Apps > Salesforce
  {label: "Salesforce Branding", link: `${setup}/Salesforce1Branding/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Mobile Quick Start", link: `${setup}/Salesforce1SetupSection/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Navigation", link: `${setup}/ProjectOneAppMenu/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Notifications", link: `${setup}/NotificationsSettings/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Offline", link: `${setup}/MobileOfflineStorageAdmin/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  {label: "Salesforce Settings", link: `${setup}/Salesforce1Settings/home`, section: "Platform Tools > Apps > Mobile Apps > Salesforce", prod: false},
  //Platform Tools > Apps > Packaging
  {label: "Installed Packages", link: `${setup}/ImportedPackage/home`, section: "Platform Tools > Apps > Packaging", prod: false},
  {label: "Package Manager", link: `${setup}/Package/home`, section: "Platform Tools > Apps > Packaging", prod: false},
  {label: "Package Usage", link: `${setup}/PackageUsageSummary/home`, section: "Platform Tools > Apps > Packaging", prod: false},

  //Platform Tools > Feature Settings > Digital Experiences
  {label: "All Sites", link: `${setup}/SetupNetworks/home`, section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Pages", link: `${setup}/CommunityFlexiPageList/home`, section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Settings", link: `${setup}/NetworkSettings/home`, section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Templates", link: `${setup}/CommunityTemplateDefinitionList/home`, section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},
  {label: "Themes", link: `${setup}/CommunityThemeDefinitionList/home`, section: "Platform Tools > Feature Settings > Digital Experiences", prod: false},

  //Platform Tools > Feature Settings
  {label: "Functions", link: `${setup}/Functions/home`, section: "Platform Tools > Feature Settings", prod: false},
  {label: "Home", link: `${setup}/Home/home`, section: "Platform Tools > Feature Settings", prod: false},
  {label: "Quip (Salesforce Anywhere)", link: `${setup}/SalesforceAnywhereSetupPage/home`, section: "Platform Tools > Feature Settings", prod: false},

  //Platform Tools > Einstein > Einstein Assessors
  {label: "Einstein Bots Assessor", link: `${setup}/EinsteinBotsReadinessCheck/home`, section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Einstein Conversation Insights Assessor", link: `${setup}/EinsteinCIReadinessCheck/home`, section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Revenue Intelligence Assessor", link: `${setup}/EinsteinRevIntlReadinessCheck/home`, section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Sales Cloud Einstein Assessor", link: `${setup}/SalesCloudEinsteinReadinessCheck/home`, section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  {label: "Service Cloud Einstein Assessor", link: `lightning/setup/ServiceCloudEinsteinReadinessCheck/home`, section: "Platform Tools > Einstein > Einstein Assessors", prod: false},
  //Platform Tools > Einstein > Einstein Platform
  {label: "Einstein Prediction Builder", link: `${setup}/EinsteinBuilder/home`, section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  {label: "Einstein Recommendation Builder", link: `${setup}/EinsteinRecommendation/home`, section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  {label: "Einstein.ai", link: `${setup}/EinsteinKeyManagement/home`, section: "Platform Tools > Einstein > Einstein Platform", prod: false},
  //Platform Tools > Einstein > Einstein Search
  {label: "Objects to Always Search", link: `${setup}/SearchScope/home`, section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Search Layouts", link: `${setup}/EinsteinSearchLayouts/home`, section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Search Manager", link: `${setup}/SearchConfiguration/home`, section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Settings", link: `${setup}/EinsteinSearchSettings/home`, section: "Platform Tools > Einstein > Einstein Search", prod: false},
  {label: "Synonyms", link: `${setup}/ManageSynonyms/home`, section: "Platform Tools > Einstein > Einstein Search", prod: false},

  //Platform Tools > Feature Settings > Salesforce Files
  {label: "Asset Files", link: `${setup}/ContentAssets/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Content Deliveries and Public Links", link: `${setup}/ContentDistribution/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Files Connect", link: `${setup}/ContentHub/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "General Settings", link: `${setup}/FilesGeneralSettings/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Regenerate Previews", link: `${setup}/RegeneratePreviews/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},
  {label: "Salesforce CRM Content", link: `${setup}/SalesforceCRMContent/home`, section: "Platform Tools > Feature Settings > Salesforce Files", prod: false},

  //Platform Tools > Feature Settings > Sales
  {label: "Activity Settings", link: `${setup}/HomeActivitiesSetupPage/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contact Roles on Contracts", link: `${setup}/ContractContactRoles/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contact Roles on Opportunities", link: `${setup}/OpportunityRoles/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Contract Settings", link: `${setup}/ContractSettings/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Individual Settings", link: `${setup}/IndividualSettings/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "LinkedIn Sales Navigator", link: `${setup}/LinkedInSalesNavigatorPage/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Notes Settings", link: `${setup}/NotesSetupPage/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Order Settings", link: `${setup}/OrderSettings/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Sales Processes", link: `${setup}/OpportunityProcess/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Social Accounts and Contacts Settings", link: `${setup}/SocialProfileOrgSettings/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},
  {label: "Update Reminders", link: `${setup}/OpportunityUpdateReminders/home`, section: "Platform Tools > Feature Settings > Sales", prod: false},

  //Platform Tools > Feature Settings > Sales > Account
  {label: "Account Settings", link: `${setup}/AccountSettings/home`, section: "Platform Tools > Feature Settings > Sales > Account", prod: false},
  {label: "Account Teams", link: `${setup}/AccountTeamSelling/home`, section: "Platform Tools > Feature Settings > Sales > Account", prod: false},
  {label: "Person Account", link: `${setup}/PersonAccountSettings/home`, section: "Platform Tools > Feature Settings > Sales > Account", prod: false},

  //Platform Tools > Feature Settings > Service
  {label: "Case Assignment Rules", link: `${setup}/CaseRules/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Auto-Response Rules", link: `${setup}/CaseResponses/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Comment Triggers", link: `${setup}/CaseCommentTriggers/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Case Team Roles", link: `${setup}/CaseTeamRoles/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Predefined Case Teams", link: `${setup}/CaseTeamTemplates/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Contact Roles on Cases", link: `${setup}/CaseContactRoles/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Customer Contact Requests", link: `${setup}/ContactRequestFlows/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Email-to-Case", link: `${setup}/EmailToCase/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Escalation Rules", link: `${setup}/CaseEscRules/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Feed Filters", link: `${setup}/FeedFilterDefinitions/home`, section: "Platform Tools > Feature Settings > Service", prod: false},

  //Platform Tools > Feature Settings > Service > Field Service
  {label: "Field Service Settings", link: `${setup}/FieldServiceSettings/home`, section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},
  {label: "Field Service Mobile App Builder", link: `${setup}/FieldServiceAppBuilder/home`, section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},
  {label: "Inbound Social Post Errors", link: `${setup}/InboundSocialPostErrors/homee`, section: "Platform Tools > Feature Settings > Service > Field Service", prod: false},

  //Platform Tools > Feature Settings > Service > Knowledge
  {label: "Data Category Assignments", link: `${setup}/KnowledgeDataCategorySetup/home`, section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Data Category Mapping", link: `${setup}/ArticleFilterRules/home`, section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Knowledge Settings", link: `${setup}/KnowledgeSettings/home`, section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},
  {label: "Validation Statuses", link: `${setup}/ValidationStatuses/home`, section: "Platform Tools > Feature Settings > Service > Knowledge", prod: false},

  {label: "Macro Settings", link: `${setup}/MacroSettings/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Omni-Channel Settings", link: `${setup}/OmniChannelSettings/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Snap-ins", link: `${setup}/Snap-ins/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Social Business Rules", link: `${setup}/SocialCustomerServiceBusinessRules/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Social Customer Service", link: `${setup}/SocialCustomerManagementAccountSettings/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Support Processes", link: `${setup}/CaseProcess/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Support Settings", link: `${setup}/CaseSettings/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Web-to-Case", link: `${setup}/CaseWebtocase/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  {label: "Web-to-Case HTML Generator", link: `${setup}/CaseWebToCaseHtmlGenerator/home`, section: "Platform Tools > Feature Settings > Service", prod: false},
  //Platform Tools > Feature Settings > Survey
  {label: "Survey Settings", link: `${setup}/SurveySettings/home`, section: "Platform Tools > Feature Settings > Survey", prod: false},
  //Platform Tools > Objects and Fields
  {label: "Object Manager", link: `${setup}/ObjectManager/home`, section: "Platform Tools > Objects and Fields", prod: false},
  {label: "Picklist Value Sets", link: `${setup}/Picklists/home`, section: "Platform Tools > Objects and Fields", prod: false},
  {label: "Schema Builder", link: `${setup}/SchemaBuilder/home`, section: "Platform Tools > Objects and Fields", prod: false},
  //Platform Tools > Events
  {label: "Event Manager", link: `${setup}/EventManager/home`, section: "Platform Tools > Events", prod: false},
  //Platform Tools > Process Automation
  {label: "Approval Processes", link: `${setup}/ApprovalProcesses/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Automation Home", link: `${setup}/ProcessHome/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Flows", link: `${setup}/Flows/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Migrate to Flow", link: `${setup}/MigrateToFlowTool/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Next Best Action", link: `${setup}/NextBestAction/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Paused And Failed Flow Interviews", link: `${setup}/Pausedflows/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Post Templates", link: `${setup}/FeedTemplates/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Process Automation Settings", link: `${setup}/WorkflowSettings/home`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Process Builder", link: `${setup}/ProcessAutomation/home`, section: "Platform Tools > Process Automation", prod: false},

  {label: "Email Alerts", link: `${setup}/WorkflowEmails/home`, section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Field Updates", link: `${setup}/WorkflowFieldUpdates/home`, section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Outbound Messages", link: `${setup}/WorkflowOutboundMessaging/home`, section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Send Actions", link: `${setup}/SendAction/home`, section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Tasks", link: `${setup}/WorkflowTasks/home`, section: "Platform Tools > Process Automation > Workflow Actions", prod: false},
  {label: "Workflow Rules", link: `${setup}/WorkflowRules/home`, section: "Platform Tools > Process Automation", prod: false},
  //User Interface
  {label: "Action Link Templates", link: `${setup}/ActionLinkGroupTemplates/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Guided Actions", link: `${setup}/GuidedActions/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "App Menu", link: `${setup}/AppMenu/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Custom Labels", link: `${setup}/ExternalStrings/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Density Settings", link: `${setup}/DensitySetup/home`, section: "Platform Tools > User Interface", prod: false},

  {label: "Global Actions", link: `${setup}/GlobalActions/home`, section: "Platform Tools > User Interface > Global Actions", prod: false},
  {label: "Publisher Layouts", link: `${setup}/GlobalPublisherLayouts/home`, section: "Platform Tools > User Interface > Global Actions", prod: false},

  {label: "Lightning App Builder", link: `${setup}/FlexiPageList/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Lightning Extension", link: `${setup}/LightningExtension/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Loaded Console Tab Limit", link: `${setup}/ConsoleMaxTabCacheSetup/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Path Settings", link: `${setup}/PathAssistantSetupHome/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Quick Text Settings", link: `${setup}/LightningQuickTextSettings/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Record Page Settings", link: `${setup}/SimpleRecordHome/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Rename Tabs and Labels", link: `${setup}/RenameTab/home`, section: "Platform Tools > User Interface", prod: false},
  //Sites and Domains
  {label: "Custom URLs", link: `${setup}/DomainSites/home`, section: "Platform Tools > User Interface > Sites and Domains", prod: false},
  {label: "Domains", link: `${setup}/DomainNames/home`, section: "Platform Tools > User Interface > Sites and Domains", prod: false},
  {label: "Sites", link: `${setup}/CustomDomain/home`, section: "Platform Tools > User Interface > Sites and Domains", prod: false},

  {label: "Tabs", link: `${setup}/CustomTabs/home`, section: "Platform Tools > User Interface", prod: false},
  {label: "Themes and Branding", link: `${setup}/ThemingAndBranding/home`, section: "Platform Tools > User Interface", prod: false},
  //Translation Workbench
  {label: "Data Translation Settings", link: `${setup}/LabelWorkbenchDataTranslationSetup/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Export", link: `${setup}/LabelWorkbenchExport/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Import", link: `${setup}/LabelWorkbenchImport/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Override", link: `${setup}/LabelWorkbenchOverride/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Translate", link: `${setup}/LabelWorkbenchTranslate/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},
  {label: "Translation Settings", link: `${setup}/LabelWorkbenchSetup/home`, section: "Platform Tools > User Interface > Translation Workbench", prod: false},

  {label: "User Interface", link: `${setup}/UserInterfaceUI/home`, section: "Platform Tools > User Interface", prod: false},
  //Custom Code
  {label: "Apex Classes", link: `${setup}/ApexClasses/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Hammer Test Results", link: `${setup}/ApexHammerResultStatus/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Settings", link: `${setup}/ApexSettings/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Test Execution", link: `${setup}/ApexTestQueue/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Test History", link: `${setup}/ApexTestHistory/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Apex Triggers", link: `${setup}/ApexTriggers/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Canvas App Previewer", link: `${setup}/CanvasPreviewerUi/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Metadata Types", link: `${setup}/CustomMetadata/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Permissions", link: `${setup}/CustomPermissions/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Custom Settings", link: `${setup}/CustomSettings/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Email Services", link: `${setup}/EmailToApexFunction/home`, section: "Platform Tools > Custom Code", prod: false},
  //Lightning Components
  {label: "Debug Mode", link: `${setup}/UserDebugModeSetup/home`, section: "Platform Tools > Custom Code > Lightning Components", prod: false},
  {label: "Lightning Components", link: `${setup}/LightningComponentBundles/home`, section: "Platform Tools > Custom Code > Lightning Components", prod: false},

  {label: "Platform Cache", link: `${setup}/PlatformCache/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Remote Access", link: `${setup}/RemoteAccess/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Static Resources", link: `${setup}/StaticResources/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Tools", link: `${setup}/ClientDevTools/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Visualforce Components", link: `${setup}/ApexComponents/home`, section: "Platform Tools > Custom Code", prod: false},
  {label: "Visualforce Pages", link: `${setup}/ApexPages/home`, section: "Platform Tools > Custom Code", prod: false},
  //Development
  {label: "Dev Hub", link: `${setup}/DevHub/home`, section: "Platform Tools > Dev Hub", prod: true},
  {label: "DevOps Center", link: `${setup}/DevOpsCenterSetup/home`, section: "Platform Tools > Dev Hub", prod: true},
  {label: "Org Shape", link: `${setup}/ShapeGrantAccess/home`, section: "Platform Tools > Dev Hub", prod: true},
  //Performance
  {label: "Performance Assistant", link: `${setup}/PerformanceAssistant/home`, section: "Platform Tools > Performance > Performance Testing", prod: false},
  //Platform Tools > Environments
  {label: "Inbound Change Sets", link: `${setup}/InboundChangeSet/home`, section: "Platform Tools > Environments > Change Sets", prod: false},
  {label: "Outbound Change Sets", link: `${setup}/OutboundChangeSet/home`, section: "Platform Tools > Environments > Change Sets", prod: false},
  //Platform Tools > Environments > Deploy
  {label: "Deployment Settings", link: `${setup}/DeploymentSettings/home`, section: "Platform Tools > Environments > Deploy", prod: false},
  {label: "Deployment Status", link: `${setup}/DeployStatus/home`, section: "Platform Tools > Environments > Deploy", prod: false},
  //Platform Tools > Environments > Jobs
  {label: "Apex Flex Queue", link: `${setup}/ApexFlexQueue/home`, section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Apex Jobs", link: `${setup}/AsyncApexJobs/home`, section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Background Jobs", link: `${setup}/ParallelJobsStatus/home`, section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Bulk Data Load Jobs", link: `${setup}/AsyncApiJobStatus/home`, section: "Platform Tools > Environments > Jobs", prod: false},
  {label: "Scheduled Jobs", link: `${setup}/ScheduledJobs/home`, section: "Platform Tools > Environments > Jobs", prod: false},
  //Platform Tools > Environments > Logs
  {label: "Debug Logs", link: `${setup}/ApexDebugLogs/home`, section: "Platform Tools > Environments > Logs", prod: false},
  {label: "Email Log Files", link: `${setup}/EmailLogFiles/home`, section: "Platform Tools > Environments > Logs", prod: false},
  //Platform Tools > Environments > Monitoring
  {label: "API Usage Notifications", link: `${setup}/MonitoringRateLimitingNotification/home`, section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Case Escalations", link: `${setup}/DataManagementManageCaseEscalation/home`, section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Email Snapshots", link: `${setup}/EmailCapture/home`, section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Outbound Messages", link: `${setup}/WorkflowOmStatus/home`, section: "Platform Tools > Environments > Monitoring", prod: false},
  {label: "Time-Based Workflow", link: `${setup}/DataManagementManageWorkflowQueue/home`, section: "Platform Tools > Environments > Monitoring", prod: false},

  {label: "Sandboxes", link: `${setup}/DataManagementCreateTestInstance/home`, section: "Platform Tools > Environments", prod: true},
  {label: "System Overview", link: `${setup}/SystemOverview/home`, section: "Platform Tools > Environments", prod: false},
  //Platform Tools > User Engagement
  {label: "Adoption Assistance", link: `${setup}/AdoptionAssistance/home`, section: "Platform Tools > User Engagement", prod: false},
  {label: "Guidance Center", link: `${setup}/LearningSetup/home`, section: "Platform Tools > User Engagement", prod: false},
  {label: "Help Menu", link: `${setup}/HelpMenu/home`, section: "Platform Tools > User Engagement", prod: false},
  {label: "In-App Guidance", link: `${setup}/Prompts/home`, section: "Platform Tools > User Engagement", prod: false},
  //Platform Tools > Integrations
  {label: "API", link: `${setup}/WebServices/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Basic Data Import", link: `${setup}/BasicDataImport/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Change Data Capture", link: `${setup}/CdcObjectEnablement/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Data Import Wizard", link: `${setup}/DataManagementDataImporter/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Data Loader", link: `${setup}/DataLoader/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Dataloader.io", link: `${setup}/DataLoaderIo/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "External Data Sources", link: `${setup}/ExternalDataSource/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "External Objects", link: `${setup}/ExternalObjects/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "External Services", link: `${setup}/ExternalServices/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Platform Events", link: `${setup}/EventObjects/home`, section: "Platform Tools > Integrations", prod: false},
  {label: "Teams Integration", link: `${setup}/MicrosoftTeamsIntegration/home`, section: "Platform Tools > Integrations", prod: false},
  //Platform Tools > Notification Builder
  {label: "Custom Notifications", link: `${setup}/CustomNotifications/home`, section: "Platform Tools > Notification Builder", prod: false},
  {label: "Notification Delivery Settings", link: `${setup}/NotificationTypesManager/home`, section: "Platform Tools > Notification Builder", prod: false},
  //Settings > Company Settings
  {label: "Business Hours", link: `${setup}/BusinessHours/home`, section: "Settings > Company Settings", prod: false},
  {label: "Public Calendars and Resources", link: `${setup}/Calendars/home`, section: "Settings > Company Settings > Calendar Settings", prod: false},
  {label: "Company Information", link: `${setup}/CompanyProfileInfo/home`, section: "Settings > Company Settings", prod: false},
  {label: "Data Protection and Privacy", link: `${setup}/ConsentManagement/home`, section: "Settings > Company Settings", prod: false},
  {label: "Fiscal Year", link: `${setup}/ForecastFiscalYear/home`, section: "Settings > Company Settings", prod: false},
  {label: "Holidays", link: `${setup}/Holiday/home`, section: "Settings > Company Settings", prod: false},
  {label: "Language Settings", link: `${setup}/LanguageSettings/home`, section: "Settings > Company Settings", prod: false},
  {label: "Manage Currencies", link: `${setup}/CompanyCurrency/home`, section: "Settings > Company Settings", prod: false},
  {label: "Maps and Location Settings", link: `${setup}/MapsAndLocationServicesSettings/home`, section: "Settings > Company Settings", prod: false},
  {label: "My Domain", link: `${setup}/OrgDomain/home`, section: "Settings > Company Settings", prod: false},
  //Settings > Data Classification
  {label: "Data Classification", link: `${setup}/DataClassificationSettings/home`, section: "Settings > Data Classification", prod: false},
  {label: "Data Classification Download", link: `${setup}/DataClassificationDownload/home`, section: "Settings > Data Classification", prod: false},
  {label: "Data Classification Upload", link: `${setup}/DataClassificationUpload/home`, section: "Settings > Data Classification", prod: false},
  //Settings > Privacy Center
  {label: "Consent Event Stream", link: `${setup}/ConsentEventStream/home`, section: "Settings > Privacy Center", prod: false},
  //Settings > Identity
  {label: "Auth. Providers", link: `${setup}/AuthProviders/home`, section: "Settings > Identity", prod: false},
  {label: "Identity Provider", link: `${setup}/IdpPage/home`, section: "Settings > Identity", prod: false},
  {label: "Identity Provider Event Log", link: `${setup}/IdpErrorLog/home`, section: "Settings > Identity", prod: false},
  {label: "Identity Verification", link: `${setup}/IdentityVerification/home`, section: "Settings > Identity", prod: false},
  {label: "Identity Verification History", link: `${setup}/VerificationHistory/home`, section: "Settings > Identity", prod: false},
  {label: "Login Flows", link: `${setup}/LoginFlow/home`, section: "Settings > Identity", prod: false},
  {label: "Login History", link: `${setup}/OrgLoginHistory/home`, section: "Settings > Identity", prod: false},
  {label: "OAuth Custom Scopes", link: `${setup}/OauthCustomScope/home`, section: "Settings > Identity", prod: false},
  {label: "OAuth and OpenID Connect Settings", link: `${setup}/OauthOidcSettings/home`, section: "Settings > Identity", prod: false},
  {label: "Single Sign-On Settings", link: `${setup}/SingleSignOn/home`, section: "Settings > Identity", prod: false},
  //Settings > Security
  {label: "Account Owner Report", link: `${setup}/SecurityAccountOwner/home`, section: "Settings > Security", prod: false},
  {label: "Activations", link: `${setup}/ActivatedIpAddressAndClientBrowsersPage/home`, section: "Settings > Security", prod: false},
  {label: "CORS", link: `${setup}/CorsWhitelistEntries/home`, section: "Settings > Security", prod: false},
  {label: "CSP Trusted Sites", link: `${setup}/SecurityCspTrustedSite/home`, section: "Settings > Security", prod: false},
  {label: "Certificate and Key Management", link: `${setup}/CertificatesAndKeysManagement/home`, section: "Settings > Security", prod: false},
  {label: "Delegated Administration", link: `${setup}/DelegateGroups/home`, section: "Settings > Security", prod: false},
  //Settings > Security > Event Monitoring
  {label: "Event Monitoring Settings", link: `${setup}/EventMonitoringSetup/home`, section: "Settings > Security > Event Monitoring", prod: false},
  {label: "Transaction Security Policies", link: `${setup}/TransactionSecurityNew/home`, section: "Settings > Security > Event Monitoring", prod: false},
  //Settings > Security
  {label: "Expire All Passwords", link: `${setup}/SecurityExpirePasswords/home`, section: "Settings > Security", prod: false},
  {label: "Field Accessibility", link: `${setup}/FieldAccessibility/home`, section: "Settings > Security", prod: false},
  {label: "File Upload and Download Security", link: `${setup}/FileTypeSetting/home`, section: "Settings > Security", prod: false},
  {label: "Health Check", link: `${setup}/HealthCheck/home`, section: "Settings > Security", prod: false},
  {label: "Login Access Policies", link: `${setup}/LoginAccessPolicies/home`, section: "Settings > Security", prod: false},
  {label: "Named Credentials", link: `${setup}/NamedCredential/home`, section: "Settings > Security", prod: false},
  {label: "Network Access", link: `${setup}/NetworkAccess/home`, section: "Settings > Security", prod: false},
  {label: "Password Policies", link: `${setup}/SecurityPolicies/home`, section: "Settings > Security", prod: false},
  //Settings > Security > Platform Encryption
  {label: "Advanced Settings", link: `${setup}/SecurityRemoteProxy/home`, section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Encryption Policy", link: `${setup}/EncryptionPolicy/home`, section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Encryption Statistics", link: `${setup}/EncryptionStatistics/home`, section: "Settings > Security > Platform Encryption", prod: false},
  {label: "Key Management", link: `${setup}/PlatformEncryptionKeyManagement/home`, section: "Settings > Security > Platform Encryption", prod: false},
  //Settings > Security
  {label: "Portal Health Check", link: `${setup}/PortalSecurityReport/home`, section: "Settings > Security", prod: false},
  {label: "Private Connect", link: `${setup}/PrivateConnect/home`, section: "Settings > Security", prod: false},
  {label: "Remote Site Settings", link: `${setup}/SecurityRemoteProxy/home`, section: "Settings > Security", prod: false},
  {label: "Session Management", link: `${setup}/SessionManagementPage/home`, section: "Settings > Security", prod: false},
  {label: "Session Settings", link: `${setup}/SecuritySession/home`, section: "Settings > Security", prod: false},
  {label: "Sharing Settings", link: `${setup}/SecuritySharing/home`, section: "Settings > Security", prod: false},
  {label: "Trusted URLs for Redirects", link: `${setup}/SecurityRedirectWhitelistUrl/home`, section: "Settings > Security", prod: false},
  {label: "View Setup Audit Trail", link: `${setup}/SecurityEvents/home`, section: "Settings > Security", prod: false},

  //Custom Link:
  {label: "Create New Flow", link: "/builder_platform_interaction/flowBuilder.app", section: "Platform Tools > Objects and Fields > New", prod: false},
  {label: "Create New Custom Object", link: `${setup}/ObjectManager/new`, section: "Platform Tools > Process Automation", prod: false},
  {label: "Create New Permission Set", link: `${setup}/PermSets/page?address=/udd/PermissionSet/newPermissionSet.apexp`, section: "Administration > Users > Permission Set", prod: false},
  {label: "Create New Custom Permission", link: `${setup}/CustomPermissions/page?address=/0CP/e`, section: "Platform Tools > Custom Code > Custom Permission", prod: false},
  {label: "Recycle Bin", link: "/lightning/o/DeleteEvent/home", section: "App Launcher > Custom Link", prod: false},

  //ConnectApi namespace classes doc links
  {label: "Class ActionLinks", link: `${apexref}/apex_ConnectAPI_ActionLinks_static_methods.htm`, section: "Documentation Apex> ConnectApi > ActionLinks", prod: false, isExternal: true},
  {label: "Class Announcements", link: `${apexref}/apex_ConnectAPI_Announcements_static_methods.htm`, section: "Documentation Apex> ConnectApi > Announcements", prod: false, isExternal: true},
  {label: "Class BotVersionActivation", link: `${apexref}/apex_ConnectAPI_BotVersionActivation_static_methods.htm`, section: "Documentation Apex> ConnectApi > BotVersionActivation", prod: false, isExternal: true},
  {label: "Class CdpCalculatedInsight", link: `${apexref}/apex_ConnectAPI_CdpCalculatedInsight_static_methods.htm`, section: "Documentation Apex> ConnectApi > CdpCalculatedInsight", prod: false, isExternal: true},
  {label: "Class CdpIdentityResolution", link: `${apexref}/apex_ConnectAPI_CdpIdentityResolution_static_methods.htm`, section: "Documentation Apex> ConnectApi > CdpIdentityResolution", prod: false, isExternal: true},
  {label: "Class CdpQuery", link: `${apexref}/apex_ConnectAPI_CdpQuery_static_methods.htm`, section: "Documentation Apex> ConnectApi > CdpQuery", prod: false, isExternal: true},
  {label: "Class CdpSegment", link: `${apexref}/apex_ConnectAPI_CdpSegment_static_methods.htm`, section: "Documentation Apex> ConnectApi > CdpSegment", prod: false, isExternal: true},
  {label: "Class Chatter", link: `${apexref}/apex_ConnectAPI_Chatter_static_methods.htm`, section: "Documentation Apex> ConnectApi > Chatter", prod: false, isExternal: true},
  {label: "Class ChatterFavorites", link: `${apexref}/apex_ConnectAPI_ChatterFavorites_static_methods.htm`, section: "Documentation Apex> ConnectApi > ChatterFavorites", prod: false, isExternal: true},
  {label: "Class ChatterFeeds", link: `${apexref}/apex_ConnectAPI_ChatterFeeds_static_methods.htm`, section: "Documentation Apex> ConnectApi > ChatterFeeds", prod: false, isExternal: true},
  {label: "Class ChatterGroups", link: `${apexref}/apex_ConnectAPI_ChatterGroups_static_methods.htm`, section: "Documentation Apex> ConnectApi > ChatterGroups", prod: false, isExternal: true},
  {label: "Class ChatterMessages", link: `${apexref}/apex_ConnectAPI_ChatterMessages_static_methods.htm`, section: "Documentation Apex> ConnectApi > ChatterMessages", prod: false, isExternal: true},
  {label: "Class ChatterUsers", link: `${apexref}/apex_ConnectAPI_ChatterUsers_static_methods.htm`, section: "Documentation Apex> ConnectApi > ChatterUsers", prod: false, isExternal: true},
  {label: "Class Clm", link: `${apexref}/apex_ConnectAPI_Clm_static_methods.htm`, section: "Documentation Apex> ConnectApi > Clm", prod: false, isExternal: true},
  {label: "Class CommerceBuyerExperience", link: `${apexref}/apex_ConnectAPI_CommerceBuyerExperience_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceBuyerExperience", prod: false, isExternal: true},
  {label: "Class CommerceCart", link: `${apexref}/apex_ConnectAPI_CommerceCart_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceCart", prod: false, isExternal: true},
  {label: "Class CommerceCatalog", link: `${apexref}/apex_ConnectAPI_CommerceCatalog_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceCatalog", prod: false, isExternal: true},
  {label: "Class CommercePromotions", link: `${apexref}/apex_ConnectAPI_CommercePromotions_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommercePromotions", prod: false, isExternal: true},
  {label: "Class CommerceSearch", link: `${apexref}/apex_ConnectAPI_CommerceSearch_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceSearch", prod: false, isExternal: true},
  {label: "Class CommerceSearchConnectFamily", link: `${apexref}/apex_ConnectAPI_CommerceSearchConnectFamily_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceSearchConnectFamily", prod: false, isExternal: true},
  {label: "Class CommerceSearchSettings", link: `${apexref}/apex_ConnectAPI_CommerceSearchSettings_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceSearchSettings", prod: false, isExternal: true},
  {label: "Class CommerceStorePricing", link: `${apexref}/apex_ConnectAPI_CommerceStorePricing_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceStorePricing", prod: false, isExternal: true},
  {label: "Class CommerceWishlist", link: `${apexref}/apex_ConnectAPI_CommerceWishlist_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommerceWishlist", prod: false, isExternal: true},
  {label: "Class Communities", link: `${apexref}/apex_ConnectAPI_Communities_static_methods.htm`, section: "Documentation Apex> ConnectApi > Communities", prod: false, isExternal: true},
  {label: "Class CommunityModeration", link: `${apexref}/apex_ConnectAPI_CommunityModeration_static_methods.htm`, section: "Documentation Apex> ConnectApi > CommunityModeration", prod: false, isExternal: true},
  {label: "Class ContentHub", link: `${apexref}/apex_ConnectAPI_ContentHub_static_methods.htm`, section: "Documentation Apex> ConnectApi > ContentHub", prod: false, isExternal: true},
  {label: "Class ConversationApplicationDefinition", link: `${apexref}/apex_ConnectAPI_ConversationApplicationDefinition_static_methods.htm`, section: "Documentation Apex> ConnectApi > ConversationApplicationDefinition", prod: false, isExternal: true},
  {label: "Class Datacloud", link: `${apexref}/apex_ConnectAPI_Datacloud_static_methods.htm`, section: "Documentation Apex> ConnectApi > Datacloud", prod: false, isExternal: true},
  {label: "Class EmailMergeFieldService", link: `${apexref}/apex_ConnectAPI_EmailMergeFieldService_static_methods.htm`, section: "Documentation Apex> ConnectApi > EmailMergeFieldService", prod: false, isExternal: true},
  {label: "Class EmployeeProfiles", link: `${apexref}/apex_ConnectAPI_EmployeeProfiles_static_methods.htm`, section: "Documentation Apex> ConnectApi > EmployeeProfiles", prod: false, isExternal: true},
  {label: "Class ExternalEmailServices", link: `${apexref}/apex_ConnectAPI_ExternalEmailService_static_methods.htm`, section: "Documentation Apex> ConnectApi > ExternalEmailServices", prod: false, isExternal: true},
  {label: "Class ExternalManagedAccount", link: `${apexref}/apex_ConnectAPI_ExternalManagedAccount_static_methods.htm`, section: "Documentation Apex> ConnectApi > ExternalManagedAccount", prod: false, isExternal: true},
  {label: "Class FieldService", link: `${apexref}/apex_ConnectAPI_FieldService_static_methods.htm`, section: "Documentation Apex> ConnectApi > FieldService", prod: false, isExternal: true},
  {label: "Class FulfillmentOrder", link: `${apexref}/apex_ConnectAPI_FulfillmentOrder_static_methods.htm`, section: "Documentation Apex> ConnectApi > FulfillmentOrder", prod: false, isExternal: true},
  {label: "Class Knowledge", link: `${apexref}/apex_ConnectAPI_Knowledge_static_methods.htm`, section: "Documentation Apex> ConnectApi > Knowledge", prod: false, isExternal: true},
  {label: "Class LightningScheduler", link: `${apexref}/apex_ConnectAPI_LightningScheduler_static_methods.htm`, section: "Documentation Apex> ConnectApi > LightningScheduler", prod: false, isExternal: true},
  {label: "Class ManagedContent", link: `${apexref}/apex_ConnectAPI_ManagedContent_static_methods.htm`, section: "Documentation Apex> ConnectApi > ManagedContent", prod: false, isExternal: true},
  {label: "Class ManagedContentDelivery", link: "", section: "Documentation Apex> ConnectApi > ManagedContentDelivery", prod: false, isExternal: true},
  {label: "Class ManagedTopics", link: `${apexref}/apex_ConnectAPI_ManagedTopics_static_methods.htm`, section: "Documentation Apex> ConnectApi > ManagedTopics", prod: false, isExternal: true},
  {label: "Class MarketingIntegration", link: `${apexref}/apex_ConnectAPI_MarketingIntegration_static_methods.htm`, section: "Documentation Apex> ConnectApi > MarketingIntegration", prod: false, isExternal: true},
  {label: "Class Mentions", link: `${apexref}/apex_ConnectAPI_Mentions_static_methods.htm`, section: "Documentation Apex> ConnectApi > Mentions", prod: false, isExternal: true},
  {label: "Class Missions", link: `${apexref}/apex_ConnectAPI_Missions_static_methods.htm`, section: "Documentation Apex> ConnectApi > Missions", prod: false, isExternal: true},
  {label: "Class NamedCredentials", link: `${apexref}/apex_ConnectAPI_NamedCredentials_static_methods.htm`, section: "Documentation Apex> ConnectApi > NamedCredentials", prod: false, isExternal: true},
  {label: "Class NavigationMenu", link: `${apexref}/apex_ConnectAPI_NavigationMenu_static_methods.htm`, section: "Documentation Apex> ConnectApi > NavigationMenu", prod: false, isExternal: true},
  {label: "Class NextBestAction", link: `${apexref}/apex_ConnectAPI_NextBestAction_static_methods.htm`, section: "Documentation Apex> ConnectApi > NextBestAction", prod: false, isExternal: true},
  {label: "Class OmnichannelInventoryService", link: `${apexref}/apex_ConnectAPI_OmnichannelInventoryService_static_methods.htm`, section: "Documentation Apex> ConnectApi > OmnichannelInventoryService", prod: false, isExternal: true},
  {label: "Class Orchestration", link: `${apexref}/apex_ConnectAPI_Orchestration_static_methods.htm`, section: "Documentation Apex> ConnectApi > Orchestration", prod: false, isExternal: true},
  {label: "Class OrderPaymentSummary", link: `${apexref}/apex_ConnectAPI_OrderPaymentSummary_static_methods.htm`, section: "Documentation Apex> ConnectApi > OrderPaymentSummary", prod: false, isExternal: true},
  {label: "Class OrderSummary", link: `${apexref}/apex_ConnectAPI_OrderSummary_static_methods.htm`, section: "Documentation Apex> ConnectApi > OrderSummary", prod: false, isExternal: true},
  {label: "Class OrderSummaryCreation", link: `${apexref}/apex_ConnectAPI_OrderSummaryCreation_static_methods.htm`, section: "Documentation Apex> ConnectApi > OrderSummaryCreation", prod: false, isExternal: true},
  {label: "Class Organization", link: `${apexref}/apex_ConnectAPI_Organization_static_methods.htm`, section: "Documentation Apex> ConnectApi > Organization", prod: false, isExternal: true},
  {label: "Class PardotBusinessUnitContext", link: `${apexref}/apex_ConnectAPI_PardotBusinessUnitContext_static_methods.htm`, section: "Documentation Apex> ConnectApi > PardotBusinessUnitContext", prod: false, isExternal: true},
  {label: "Class Payments", link: `${apexref}/apex_ConnectAPI_Payments_static_methods.htm`, section: "Documentation Apex> ConnectApi > Payments", prod: false, isExternal: true},
  {label: "Class Personalization", link: `${apexref}/apex_ConnectAPI_Personalization_static_methods.htm`, section: "Documentation Apex> ConnectApi > Personalization", prod: false, isExternal: true},
  {label: "Class PickTicket", link: `${apexref}/apex_ConnectAPI_PickTicket_static_methods.htm`, section: "Documentation Apex> ConnectApi > PickTicket", prod: false, isExternal: true},
  {label: "Class QuestionAndAnswers", link: `${apexref}/apex_ConnectAPI_QuestionAndAnswers_static_methods.htm`, section: "Documentation Apex> ConnectApi > QuestionAndAnswers", prod: false, isExternal: true},
  {label: "Class Recommendations", link: `${apexref}/apex_ConnectAPI_Recommendations_static_methods.htm`, section: "Documentation Apex> ConnectApi > Recommendations", prod: false, isExternal: true},
  {label: "Class Records", link: `${apexref}/apex_ConnectAPI_Records_static_methods.htm`, section: "Documentation Apex> ConnectApi > Records", prod: false, isExternal: true},
  {label: "Class Repricing", link: `${apexref}/apex_ConnectAPI_Repricing_static_methods.htm`, section: "Documentation Apex> ConnectApi > Repricing", prod: false, isExternal: true},
  {label: "Class ReturnOrder", link: `${apexref}/apex_ConnectAPI_ReturnOrder_static_methods.htm`, section: "Documentation Apex> ConnectApi > ReturnOrder", prod: false, isExternal: true},
  {label: "Class Routing", link: `${apexref}/apex_ConnectAPI_Routing_static_methods.htm`, section: "Documentation Apex> ConnectApi > Routing", prod: false, isExternal: true},
  {label: "Class SalesforceInbox", link: `${apexref}/apex_ConnectAPI_SalesforceInbox_static_methods.htm`, section: "Documentation Apex> ConnectApi > SalesforceInbox", prod: false, isExternal: true},
  {label: "Class Sites", link: `${apexref}/apex_ConnectAPI_Sites_static_methods.htm`, section: "Documentation Apex> ConnectApi > Sites", prod: false, isExternal: true},
  {label: "Class SocialEngagement", link: `${apexref}/apex_ConnectAPI_SocialEngagement_static_methods.htm`, section: "Documentation Apex> ConnectApi > SocialEngagement", prod: false, isExternal: true},
  {label: "Class Surveys", link: `${apexref}/apex_ConnectAPI_Survey_static_methods.htm`, section: "Documentation Apex> ConnectApi > Surveys", prod: false, isExternal: true},
  {label: "Class TaxPlatform", link: `${apexref}/apex_ConnectAPI_TaxPlatform_static_methods.htm`, section: "Documentation Apex> ConnectApi > TaxPlatform", prod: false, isExternal: true},
  {label: "Class Topics", link: `${apexref}/apex_ConnectAPI_Topics_static_methods.htm`, section: "Documentation Apex> ConnectApi > Topics", prod: false, isExternal: true},
  {label: "Class UserProfiles", link: `${apexref}/apex_ConnectAPI_UserProfiles_static_methods.htm`, section: "Documentation Apex> ConnectApi > UserProfiles", prod: false, isExternal: true},
  {label: "Class Zones", link: `${apexref}/apex_ConnectAPI_Zones_static_methods.htm`, section: "Documentation Apex> ConnectApi > Zones", prod: false, isExternal: true},
  {label: "Class ConnectApi Input", link: `${apexref}/apex_connectapi_input.htm`, section: "Documentation Apex> ConnectApi > ActionLinks", prod: false, isExternal: true},
  {label: "Class ConnectApi Output", link: `${apexref}/apex_connectapi_output.htm`, section: "Documentation Apex> ConnectApi > ConnectApi Output", prod: false, isExternal: true},
  //Database namespace classes doc links
  {label: "Class Batchable", link: `${apexref}/apex_interface_database_batchable.htm`, section: "Documentation Apex> Database > Batchable", prod: false, isExternal: true},
  {label: "Class BatchableContext", link: `${apexref}/apex_interface_database_batchablecontext.htm`, section: "Documentation Apex> Database > BatchableContext", prod: false, isExternal: true},
  {label: "Class DeletedRecord", link: `${apexref}/apex_class_database_deletedrecord.htm`, section: "Documentation Apex> Database > DeletedRecord", prod: false, isExternal: true},
  {label: "Class DeleteResult", link: `${apexref}/apex_methods_system_database_deleteresult.htm`, section: "Documentation Apex> Database > DeleteResult", prod: false, isExternal: true},
  {label: "Class DMLOptions", link: `${apexref}/apex_methods_system_database_dmloptions.htm`, section: "Documentation Apex> Database > DMLOptions", prod: false, isExternal: true},
  {label: "Class DuplicateError", link: `${apexref}/apex_class_Database_DuplicateError.htm`, section: "Documentation Apex> Database > DuplicateError", prod: false, isExternal: true},
  {label: "Class EmptyRecycleBinResult", link: `${apexref}/apex_methods_system_database_EmptyRecycleBinResult.htm`, section: "Documentation Apex> Database > EmptyRecycleBinResult", prod: false, isExternal: true},
  {label: "Class Error", link: `${apexref}/apex_methods_system_database_error.htm`, section: "Documentation Apex> Database > Error", prod: false, isExternal: true},
  {label: "Class GetDeletedResult", link: `${apexref}/apex_class_database_getdeletedresult.htm`, section: "Documentation Apex> Database > GetDeletedResult", prod: false, isExternal: true},
  {label: "Class GetUpdatedResult", link: `${apexref}/apex_class_database_getupdatedresult.htm`, section: "Documentation Apex> Database > GetUpdatedResult", prod: false, isExternal: true},
  {label: "Class LeadConvert", link: `${apexref}/apex_dml_convertLead.htm`, section: "Documentation Apex> Database > LeadConvert", prod: false, isExternal: true},
  {label: "Class LeadConvertResult", link: `${apexref}/apex_class_database_leadconvertresult.htm`, section: "Documentation Apex> Database > LeadConvertResult", prod: false, isExternal: true},
  {label: "Class MergeResult", link: `${apexref}/apex_class_database_mergeresult.htm`, section: "Documentation Apex> Database > MergeResult", prod: false, isExternal: true},
  {label: "Class QueryLocator", link: `${apexref}/apex_methods_system_database_batch.htm`, section: "Documentation Apex> Database > QueryLocator", prod: false, isExternal: true},
  {label: "Class QueryLocatorIterator", link: `${apexref}/apex_class_database_querylocatoriterator.htm`, section: "Documentation Apex> Database > QueryLocatorIterator", prod: false, isExternal: true},
  {label: "Class SaveResult", link: `${apexref}/apex_methods_system_database_saveresult.htm`, section: "Documentation Apex> Database > SaveResult", prod: false, isExternal: true},
  {label: "Class UndeleteResult", link: `${apexref}/apex_methods_system_database_undeleteresult.htm`, section: "Documentation Apex> Database > UndeleteResult", prod: false, isExternal: true},
  {label: "Class UpsertResult", link: `${apexref}/apex_methods_system_database_upsertresult.htm`, section: "Documentation Apex> Database > UpsertResult", prod: false, isExternal: true},
  //System namespace classes doc links
  {label: "Class AccessLevel", link: `${apexref}/apex_class_System_AccessLevel.htm`, section: "Documentation Apex> System > AccessLevel", prod: false, isExternal: true},
  {label: "Class Address", link: `${apexref}/apex_class_system_Address.htm`, section: "Documentation Apex> System > Address", prod: false, isExternal: true},
  {label: "Class Answers", link: `${apexref}/apex_classes_answers.htm`, section: "Documentation Apex> System > Answers", prod: false, isExternal: true},
  {label: "Class ApexPages", link: `${apexref}/apex_methods_system_apexpages.htm`, section: "Documentation Apex> System > ApexPages", prod: false, isExternal: true},
  {label: "Class Approval", link: `${apexref}/apex_methods_system_approval.htm`, section: "Documentation Apex> System > Approval", prod: false, isExternal: true},
  {label: "Class Assert", link: `${apexref}/apex_class_System_Assert.htm`, section: "Documentation Apex> System > Assert", prod: false, isExternal: true},
  {label: "Class AsyncInfo", link: `${apexref}/apex_class_System_AsyncInfo.htm`, section: "Documentation Apex> System > AsyncInfo", prod: false, isExternal: true},
  {label: "Class AsyncOptions", link: `${apexref}/apex_class_System_AsyncOptions.htm`, section: "Documentation Apex> System > AsyncOptions", prod: false, isExternal: true},
  {label: "Class Blob", link: `${apexref}/apex_methods_system_blob.htm`, section: "Documentation Apex> System > Blob", prod: false, isExternal: true},
  {label: "Class Boolean", link: `${apexref}/apex_methods_system_boolean.htm`, section: "Documentation Apex> System > Boolean", prod: false, isExternal: true},
  {label: "Class BusinessHours", link: `${apexref}/apex_classes_businesshours.htm`, section: "Documentation Apex> System > BusinessHours", prod: false, isExternal: true},
  {label: "Class Callable", link: `${apexref}/apex_interface_System_Callable.htm`, section: "Documentation Apex> System > Callable", prod: false, isExternal: true},
  {label: "Class Cases", link: `${apexref}/apex_System_Cases_methods.htm`, section: "Documentation Apex> System > Cases", prod: false, isExternal: true},
  {label: "Class Collator", link: `${apexref}/apex_class_System_Collator.htm`, section: "Documentation Apex> System > Collator", prod: false, isExternal: true},
  {label: "Class Comparable", link: `${apexref}/apex_comparable.htm`, section: "Documentation Apex> System > Comparable", prod: false, isExternal: true},
  {label: "Class Comparator", link: `${apexref}/apex_interface_System_Comparator.htm`, section: "Documentation Apex> System > Comparator", prod: false, isExternal: true},
  {label: "Class Continuation", link: `${apexref}/apex_class_System_Continuation.htm`, section: "Documentation Apex> System > Continuation", prod: false, isExternal: true},
  {label: "Class Cookie", link: `${apexref}/apex_classes_sites_cookie.htm`, section: "Documentation Apex> System > Cookie", prod: false, isExternal: true},
  {label: "Class Crypto", link: `${apexref}/apex_classes_restful_crypto.htm`, section: "Documentation Apex> System > Crypto", prod: false, isExternal: true},
  {label: "Class Custom Metadata Type", link: `${apexref}/apex_methods_system_custom_metadata_types.htm`, section: "Documentation Apex> System > Custom Metadata Type", prod: false, isExternal: true},
  {label: "Class Custom Settings", link: `${apexref}/apex_methods_system_custom_settings.htm`, section: "Documentation Apex> System > Custom Settings", prod: false, isExternal: true},
  {label: "Class Database", link: `${apexref}/apex_methods_system_database.htm`, section: "Documentation Apex> System > Database", prod: false, isExternal: true},
  {label: "Class Date", link: `${apexref}/apex_methods_system_date.htm`, section: "Documentation Apex> System > Date", prod: false, isExternal: true},
  {label: "Class Datetime", link: `${apexref}/apex_methods_system_datetime.htm`, section: "Documentation Apex> System > Datetime", prod: false, isExternal: true},
  {label: "Class Decimal", link: `${apexref}/apex_methods_system_decimal.htm`, section: "Documentation Apex> System > Decimal", prod: false, isExternal: true},
  {label: "Class Domain", link: `${apexref}/apex_class_System_Domain.htm`, section: "Documentation Apex> System > Domain", prod: false, isExternal: true},
  {label: "Class DomainCreator", link: `${apexref}/apex_class_System_DomainCreator.htm`, section: "Documentation Apex> System > DomainCreator", prod: false, isExternal: true},
  {label: "Class DomainParser", link: `${apexref}/apex_class_System_DomainParser.htm`, section: "Documentation Apex> System > DomainParser", prod: false, isExternal: true},
  {label: "Class Double", link: `${apexref}/apex_methods_system_double.htm`, section: "Documentation Apex> System > Double", prod: false, isExternal: true},
  {label: "Class EmailMessages", link: `${apexref}/apex_class_system_emailmessages.htm`, section: "Documentation Apex> System > EmailMessages", prod: false, isExternal: true},
  {label: "Class EncodingUtil", link: `${apexref}/apex_classes_restful_encodingUtil.htm`, section: "Documentation Apex> System > EncodingUtil", prod: false, isExternal: true},
  {label: "Class EventBus", link: `${apexref}/apex_class_System_eventbus.htm`, section: "Documentation Apex> System > EventBus", prod: false, isExternal: true},
  {label: "Class FlexQueue", link: `${apexref}/apex_class_System_FlexQueue.htm`, section: "Documentation Apex> System > FlexQueue", prod: false, isExternal: true},
  {label: "Class FeatureManagement", link: `${apexref}/apex_class_System_FeatureManagement.htm`, section: "Documentation Apex> System > FeatureManagement", prod: false, isExternal: true},
  {label: "Class Formula", link: `${apexref}/apex_class_System_Formula.htm`, section: "Documentation Apex> System > Formula", prod: false, isExternal: true},
  {label: "Class FormulaRecalcFieldError", link: `${apexref}/apex_class_System_FormulaRecalcFieldError.htm`, section: "Documentation Apex> System > FormulaRecalcFieldError", prod: false, isExternal: true},
  {label: "Class FormulaRecalcResult", link: `${apexref}/apex_class_System_FormulaRecalcResult.htm`, section: "Documentation Apex> System > FormulaRecalcResult", prod: false, isExternal: true},
  {label: "Class Http", link: `${apexref}/apex_classes_restful_http_http.htm`, section: "Documentation Apex> System > Http", prod: false, isExternal: true},
  {label: "Class HttpCalloutMock", link: `${apexref}/apex_interface_httpcalloutmock.htm`, section: "Documentation Apex> System > HttpCalloutMock", prod: false, isExternal: true},
  {label: "Class HttpRequest", link: `${apexref}/apex_classes_restful_http_httprequest.htm`, section: "Documentation Apex> System > HttpRequest", prod: false, isExternal: true},
  {label: "Class HttpResponse", link: `${apexref}/apex_classes_restful_http_httpresponse.htm`, section: "Documentation Apex> System > HttpResponse", prod: false, isExternal: true},
  {label: "Class Id", link: `${apexref}/apex_methods_system_id.htm`, section: "Documentation Apex> System > Id", prod: false, isExternal: true},
  {label: "Class Ideas", link: `${apexref}/apex_classes_ideas.htm`, section: "Documentation Apex> System > Ideas", prod: false, isExternal: true},
  {label: "Class InstallHandler", link: `${apexref}/apex_install_handler.htm`, section: "Documentation Apex> System > InstallHandler", prod: false, isExternal: true},
  {label: "Class Integer", link: `${apexref}/apex_methods_system_integer.htm`, section: "Documentation Apex> System > Integer", prod: false, isExternal: true},
  {label: "Class JSON", link: `${apexref}/apex_class_System_Json.htm`, section: "Documentation Apex> System > JSON", prod: false, isExternal: true},
  {label: "Class JSONGenerator", link: `${apexref}/apex_class_System_JsonGenerator.htm`, section: "Documentation Apex> System > JSONGenerator", prod: false, isExternal: true},
  {label: "Class JSONParser", link: `${apexref}/apex_class_System_JsonParser.htm`, section: "Documentation Apex> System > JSONParser", prod: false, isExternal: true},
  {label: "Class Label", link: `${apexref}/apex_class_System_Label.htm`, section: "Documentation Apex> System > Label", prod: false, isExternal: true},
  {label: "Class Limits", link: `${apexref}/apex_methods_system_limits.htm`, section: "Documentation Apex> System > Limits", prod: false, isExternal: true},
  {label: "Class List", link: `${apexref}/apex_methods_system_list.htm`, section: "Documentation Apex> System > List", prod: false, isExternal: true},
  {label: "Class Location", link: `${apexref}/apex_class_system_Location.htm`, section: "Documentation Apex> System > Location", prod: false, isExternal: true},
  {label: "Class Long", link: `${apexref}/apex_methods_system_long.htm`, section: "Documentation Apex> System > Long", prod: false, isExternal: true},
  {label: "Class Map", link: `${apexref}/apex_methods_system_map.htm`, section: "Documentation Apex> System > Map", prod: false, isExternal: true},
  {label: "Class Matcher", link: `${apexref}/apex_classes_pattern_and_matcher_matcher_methods.htm`, section: "Documentation Apex> System > Matcher", prod: false, isExternal: true},
  {label: "Class Math", link: `${apexref}/apex_methods_system_math.htm`, section: "Documentation Apex> System > Math", prod: false, isExternal: true},
  {label: "Class Messaging", link: `${apexref}/apex_classes_email_outbound_messaging.htm`, section: "Documentation Apex> System > Messaging", prod: false, isExternal: true},
  {label: "Class MultiStaticResourceCalloutMock", link: `${apexref}/apex_methods_system_multistaticresourcecalloutmock.htm`, section: "Documentation Apex> System > MultiStaticResourceCalloutMock", prod: false, isExternal: true},
  {label: "Class Network", link: `${apexref}/apex_classes_network.htm`, section: "Documentation Apex> System > Network", prod: false, isExternal: true},
  {label: "Class OrgLimit", link: `${apexref}/apex_class_System_OrgLimit.htm`, section: "Documentation Apex> System > OrgLimit", prod: false, isExternal: true},
  {label: "Class OrgLimits", link: `${apexref}/apex_class_System_OrgLimits.htm`, section: "Documentation Apex> System > OrgLimits", prod: false, isExternal: true},
  {label: "Class PageReference", link: `${apexref}/apex_system_pagereference.htm`, section: "Documentation Apex> System > PageReference", prod: false, isExternal: true},
  {label: "Class Packaging", link: `${apexref}/apex_class_system_Packaging.htm`, section: "Documentation Apex> System > Packaging", prod: false, isExternal: true},
  {label: "Class Pattern", link: `${apexref}/apex_classes_pattern_and_matcher_pattern_methods.htm`, section: "Documentation Apex> System > Pattern", prod: false, isExternal: true},
  {label: "Class Queueable", link: `${apexref}/apex_class_System_Queueable.htm`, section: "Documentation Apex> System > Queueable", prod: false, isExternal: true},
  {label: "Class QueueableContext", link: `${apexref}/apex_interface_system_queueablecontext.htm`, section: "Documentation Apex> System > QueueableContext", prod: false, isExternal: true},
  {label: "Class QueueableDuplicateSignature", link: `${apexref}/apex_class_System_QueueableDuplicateSignature.htm`, section: "Documentation Apex> System > QueueableDuplicateSignature", prod: false, isExternal: true},
  {label: "Class QuickAction", link: `${apexref}/apex_class_system_quickaction.htm`, section: "Documentation Apex> System > QuickAction", prod: false, isExternal: true},
  {label: "Class RemoteObjectController", link: `${apexref}/apex_class_system_remoteobjectcontroller.htm`, section: "Documentation Apex> System > RemoteObjectController", prod: false, isExternal: true},
  {label: "Class Request", link: `${apexref}/apex_class_System_Request.htm`, section: "Documentation Apex> System > Request", prod: false, isExternal: true},
  {label: "Class ResetPasswordResult", link: `${apexref}/apex_class_System_ResetPasswordResult.htm`, section: "Documentation Apex> System > ResetPasswordResult", prod: false, isExternal: true},
  {label: "Class RestContext", link: `${apexref}/apex_methods_system_restcontext.htm`, section: "Documentation Apex> System > RestContext", prod: false, isExternal: true},
  {label: "Class RestRequest", link: `${apexref}/apex_methods_system_restrequest.htm`, section: "Documentation Apex> System > RestRequest", prod: false, isExternal: true},
  {label: "Class RestResponse", link: `${apexref}/apex_methods_system_restresponse.htm`, section: "Documentation Apex> System > RestResponse", prod: false, isExternal: true},
  {label: "Class SandboxPostCopy", link: `${apexref}/apex_interface_System_SandboxPostCopy.htm`, section: "Documentation Apex> System > SandboxPostCopy", prod: false, isExternal: true},
  {label: "Class Schedulable", link: `${apexref}/apex_interface_system_schedulable.htm`, section: "Documentation Apex> System > Schedulable", prod: false, isExternal: true},
  {label: "Class SchedulableContext", link: `${apexref}/apex_interface_system_schedulablecontext.htm`, section: "Documentation Apex> System > SchedulableContext", prod: false, isExternal: true},
  {label: "Class Schema", link: `${apexref}/apex_methods_system_schema.htm`, section: "Documentation Apex> System > Schema", prod: false, isExternal: true},
  {label: "Class Search", link: `${apexref}/apex_methods_system_search.htm`, section: "Documentation Apex> System > Search", prod: false, isExternal: true},
  {label: "Class Security", link: `${apexref}/apex_class_System_Security.htm`, section: "Documentation Apex> System > Security", prod: false, isExternal: true},
  {label: "Class SelectOption", link: `${apexref}/apex_pages_selectoption.htm`, section: "Documentation Apex> System > SelectOption", prod: false, isExternal: true},
  {label: "Class Set", link: `${apexref}/apex_methods_system_set.htm`, section: "Documentation Apex> System > Set", prod: false, isExternal: true},
  {label: "Class Site", link: `${apexref}/apex_classes_sites.htm`, section: "Documentation Apex> System > Site", prod: false, isExternal: true},
  {label: "Class SObject", link: `${apexref}/apex_methods_system_sobject.htm`, section: "Documentation Apex> System > SObject", prod: false, isExternal: true},
  {label: "Class SObjectAccessDecision", link: `${apexref}/apex_class_System_SObjectAccessDecision.htm`, section: "Documentation Apex> System > SObjectAccessDecision", prod: false, isExternal: true},
  {label: "Class StaticResourceCalloutMock", link: `${apexref}/apex_methods_system_staticresourcecalloutmock.htm`, section: "Documentation Apex> System > StaticResourceCalloutMock", prod: false, isExternal: true},
  {label: "Class String", link: `${apexref}/apex_methods_system_string.htm`, section: "Documentation Apex> System > String", prod: false, isExternal: true},
  {label: "Class StubProvider", link: `${apexref}/apex_interface_System_StubProvider.htm`, section: "Documentation Apex> System > StubProvider", prod: false, isExternal: true},
  {label: "Class System", link: `${apexref}/apex_methods_system_system.htm`, section: "Documentation Apex> System > System", prod: false, isExternal: true},
  {label: "Class Test", link: `${apexref}/apex_methods_system_test.htm`, section: "Documentation Apex> System > Test", prod: false, isExternal: true},
  {label: "Class Time", link: `${apexref}/apex_methods_system_time.htm`, section: "Documentation Apex> System > Time", prod: false, isExternal: true},
  {label: "Class TimeZone", link: `${apexref}/apex_methods_system_timezone.htm`, section: "Documentation Apex> System > TimeZone", prod: false, isExternal: true},
  {label: "Class Type", link: `${apexref}/apex_methods_system_type.htm`, section: "Documentation Apex> System > Type", prod: false, isExternal: true},
  {label: "Class UninstallHandler", link: `${apexref}/apex_uninstall_handler.htm`, section: "Documentation Apex> System > UninstallHandler", prod: false, isExternal: true},
  {label: "Class URL", link: `${apexref}/apex_methods_system_url.htm`, section: "Documentation Apex> System > URL", prod: false, isExternal: true},
  {label: "Class UserInfo", link: `${apexref}/apex_methods_system_userinfo.htm`, section: "Documentation Apex> System > UserInfo", prod: false, isExternal: true},
  {label: "Class UserManagement", link: `${apexref}/apex_class_System_UserManagement.htm`, section: "Documentation Apex> System > UserManagement", prod: false, isExternal: true},
  {label: "Class Version", link: `${apexref}/apex_methods_system_version.htm`, section: "Documentation Apex> System > Version", prod: false, isExternal: true},
  {label: "Class WebServiceCallout", link: `${apexref}/apex_class_System_WebServiceCallout.htm`, section: "Documentation Apex> System > WebServiceCallout", prod: false, isExternal: true},
  {label: "Class WebServiceMock", link: `${apexref}/apex_interface_webservicemock.htm`, section: "Documentation Apex> System > WebServiceMock", prod: false, isExternal: true},
  {label: "Class XmlStreamReader", link: `${apexref}/apex_classes_xml_XmlStream_reader.htm`, section: "Documentation Apex> System > XmlStreamReader", prod: false, isExternal: true},
  {label: "Class XmlStreamWriter", link: `${apexref}/apex_classes_xml_XmlStream_writer.htm`, section: "Documentation Apex> System > XmlStreamWriter", prod: false, isExternal: true},
  {label: "Class Boolean", link: "", section: "Documentation Apex> System > String", prod: false, isExternal: true}
];
